(()=>{
'use strict';
const REGION_LANG={fr:'fr',be:'fr',ch:'fr',gb:'en',us:'en',ca:'fr',de:'de',es:'es',it:'it',pt:'pt',nl:'nl'};
const OPTIONS=[['fr','🇫🇷 Français · France'],['be','🇧🇪 Français · Belgique'],['ch','🇨🇭 Français · Suisse'],['gb','🇬🇧 English · UK'],['us','🇺🇸 English · USA'],['ca','🇨🇦 Français · Canada'],['de','🇩🇪 Deutsch · Deutschland'],['es','🇪🇸 Español · España'],['it','🇮🇹 Italiano · Italia'],['pt','🇵🇹 Português · Portugal'],['nl','🇳🇱 Nederlands · Nederland']];
const T={
 de:{'Accueil':'Startseite','Infos Technorizon':'Infos Technorizon','Contact':'Kontakt','Jeux':'Spiele','La musique sans frontières':'Musik ohne Grenzen','En ce moment sur Technorizon':'Jetzt auf Technorizon','Infos':'Nachrichten','Voir toutes les infos →':'Alle Nachrichten →','Météo':'Wetter','Voir les prévisions →':'Vorhersage ansehen →','Votre horoscope du jour':'Dein Tageshoroskop','12 signes • version Technorizon':'12 Zeichen • Technorizon-Ausgabe','Découvrir mon Technoroscope':'Mein Technoroscope entdecken','Écoutez Technorizon partout':'Technorizon überall hören','Dédicaces':'Widmungen','Technorizon.fr, la web-radio Techno, Eurodance et House':'Technorizon.fr, das Webradio für Techno, Eurodance und House','Écoutez gratuitement une programmation musicale en continu, des années 90 à aujourd’hui : Techno, Eurodance, House, Dance Pop et Electro, 24h/24 et 7j/7.':'Kostenlos nonstop Musik von den 90ern bis heute hören: Techno, Eurodance, House, Dance Pop und Electro, rund um die Uhr.','Écoutez plus loin…':'Weiterhören…','Conception & réalisation : Studio Gaby Design':'Konzeption & Entwicklung: Studio Gaby Design'},
 es:{'Accueil':'Inicio','Infos Technorizon':'Información Technorizon','Contact':'Contacto','Jeux':'Juegos','La musique sans frontières':'La música sin fronteras','En ce moment sur Technorizon':'Ahora en Technorizon','Infos':'Noticias','Voir toutes les infos →':'Ver todas las noticias →','Météo':'Tiempo','Voir les prévisions →':'Ver previsión →','Votre horoscope du jour':'Tu horóscopo diario','12 signes • version Technorizon':'12 signos • edición Technorizon','Découvrir mon Technoroscope':'Descubrir mi Technoroscope','Écoutez Technorizon partout':'Escucha Technorizon en todas partes','Dédicaces':'Dedicatorias','Technorizon.fr, la web-radio Techno, Eurodance et House':'Technorizon.fr, la web radio de Techno, Eurodance y House','Écoutez gratuitement une programmation musicale en continu, des années 90 à aujourd’hui : Techno, Eurodance, House, Dance Pop et Electro, 24h/24 et 7j/7.':'Escucha gratis música sin parar desde los 90 hasta hoy: Techno, Eurodance, House, Dance Pop y Electro, 24/7.','Écoutez plus loin…':'Escucha más allá…','Conception & réalisation : Studio Gaby Design':'Diseño y desarrollo: Studio Gaby Design'},
 it:{'Accueil':'Home','Infos Technorizon':'Info Technorizon','Contact':'Contatti','Jeux':'Giochi','La musique sans frontières':'La musica senza confini','En ce moment sur Technorizon':'Ora su Technorizon','Infos':'Notizie','Voir toutes les infos →':'Vedi tutte le notizie →','Météo':'Meteo','Voir les prévisions →':'Vedi previsioni →','Votre horoscope du jour':'Il tuo oroscopo del giorno','12 signes • version Technorizon':'12 segni • edizione Technorizon','Découvrir mon Technoroscope':'Scopri il mio Technoroscope','Écoutez Technorizon partout':'Ascolta Technorizon ovunque','Dédicaces':'Dediche','Technorizon.fr, la web-radio Techno, Eurodance et House':'Technorizon.fr, la web radio Techno, Eurodance e House','Écoutez gratuitement une programmation musicale en continu, des années 90 à aujourd’hui : Techno, Eurodance, House, Dance Pop et Electro, 24h/24 et 7j/7.':'Ascolta gratis musica non-stop dagli anni 90 a oggi: Techno, Eurodance, House, Dance Pop ed Electro, 24/7.','Écoutez plus loin…':'Ascolta oltre…','Conception & réalisation : Studio Gaby Design':'Ideazione e sviluppo: Studio Gaby Design'},
 pt:{'Accueil':'Início','Infos Technorizon':'Info Technorizon','Contact':'Contacto','Jeux':'Jogos','La musique sans frontières':'A música sem fronteiras','En ce moment sur Technorizon':'Agora na Technorizon','Infos':'Notícias','Voir toutes les infos →':'Ver todas as notícias →','Météo':'Meteorologia','Voir les prévisions →':'Ver previsão →','Votre horoscope du jour':'O teu horóscopo do dia','12 signes • version Technorizon':'12 signos • edição Technorizon','Découvrir mon Technoroscope':'Descobrir o meu Technoroscope','Écoutez Technorizon partout':'Ouve Technorizon em todo o lado','Dédicaces':'Dedicatórias','Technorizon.fr, la web-radio Techno, Eurodance et House':'Technorizon.fr, a web rádio Techno, Eurodance e House','Écoutez gratuitement une programmation musicale en continu, des années 90 à aujourd’hui : Techno, Eurodance, House, Dance Pop et Electro, 24h/24 et 7j/7.':'Ouve gratuitamente música sem parar dos anos 90 até hoje: Techno, Eurodance, House, Dance Pop e Electro, 24/7.','Écoutez plus loin…':'Ouve mais longe…','Conception & réalisation : Studio Gaby Design':'Conceção e desenvolvimento: Studio Gaby Design'},
 nl:{'Accueil':'Start','Infos Technorizon':'Info Technorizon','Contact':'Contact','Jeux':'Spellen','La musique sans frontières':'Muziek zonder grenzen','En ce moment sur Technorizon':'Nu op Technorizon','Infos':'Nieuws','Voir toutes les infos →':'Bekijk al het nieuws →','Météo':'Weer','Voir les prévisions →':'Bekijk verwachting →','Votre horoscope du jour':'Je dagelijkse horoscoop','12 signes • version Technorizon':'12 tekens • Technorizon-editie','Découvrir mon Technoroscope':'Ontdek mijn Technoroscope','Écoutez Technorizon partout':'Luister overal naar Technorizon','Dédicaces':'Opdrachten','Technorizon.fr, la web-radio Techno, Eurodance et House':'Technorizon.fr, de webradio voor Techno, Eurodance en House','Écoutez gratuitement une programmation musicale en continu, des années 90 à aujourd’hui : Techno, Eurodance, House, Dance Pop et Electro, 24h/24 et 7j/7.':'Luister gratis naar non-stop muziek van de jaren 90 tot nu: Techno, Eurodance, House, Dance Pop en Electro, 24/7.','Écoutez plus loin…':'Luister verder…','Conception & réalisation : Studio Gaby Design':'Ontwerp & ontwikkeling: Studio Gaby Design'}
};
const box=document.querySelector('.v2-language'); if(!box)return;
const select=document.createElement('select');select.id='siteLanguage';select.className='lang-select';select.setAttribute('aria-label','Langue et région');OPTIONS.forEach(([v,n])=>select.add(new Option(n,v)));
box.innerHTML='';box.appendChild(select);
const style=document.createElement('style');style.textContent='.v2-language .lang-select{min-width:190px;max-width:235px;padding:9px 48px 9px 13px;border:1px solid rgba(0,234,255,.32);border-radius:999px;background-color:#071525;color:#dffcff;font-size:12px;font-weight:700;cursor:pointer;appearance:none;-webkit-appearance:none;background-image:url("data:image/svg+xml,%3Csvg xmlns=%27http://www.w3.org/2000/svg%27 width=%2712%27 height=%278%27 viewBox=%270 0 12 8%27%3E%3Cpath d=%27M1 1l5 5 5-5%27 fill=%27none%27 stroke=%27%2300eaff%27 stroke-width=%271.6%27 stroke-linecap=%27round%27/%3E%3C/svg%3E");background-repeat:no-repeat;background-position:right 18px center;background-size:12px 8px}.v2-language .lang-select:focus{outline:2px solid rgba(0,234,255,.42);outline-offset:2px}@media(max-width:600px){.v2-language .lang-select{min-width:175px;max-width:210px}}';document.head.appendChild(style);
const originals=new Map();document.querySelectorAll('[data-fr][data-en]').forEach(el=>originals.set(el,el.dataset.fr));
function apply(region){const l=REGION_LANG[region]||'fr';localStorage.setItem('technorizon-region',region);localStorage.setItem('technorizon-lang',l);document.documentElement.lang=l;select.value=region;
 document.querySelectorAll('[data-fr][data-en]').forEach(el=>{const fr=originals.get(el)||el.dataset.fr;if(l==='fr')el.textContent=el.dataset.fr;else if(l==='en')el.textContent=el.dataset.en;else el.textContent=(T[l]&&T[l][fr])||el.dataset.en||fr});
 const share=document.getElementById('v2-share');if(share){const labels={fr:'Partager Technorizon.fr',en:'Share Technorizon.fr',de:'Technorizon.fr teilen',es:'Compartir Technorizon.fr',it:'Condividi Technorizon.fr',pt:'Partilhar Technorizon.fr',nl:'Technorizon.fr delen'};share.title=share.getAttribute('aria-label')=labels[l]||labels.en;}
 window.dispatchEvent(new CustomEvent('technorizon-region-change',{detail:{region,lang:l}}));}
let saved=localStorage.getItem('technorizon-region');if(!REGION_LANG[saved]){const old=localStorage.getItem('technorizon-lang');saved=old==='en'?'gb':REGION_LANG[old]?old:'fr'}
select.addEventListener('change',()=>apply(select.value));apply(saved);
})();