(() => {
  const avatar='JayaV2.jpg';
  const css=`
  .jaya-fab{position:fixed;right:22px;bottom:22px;z-index:1000;width:66px;height:66px;padding:0;overflow:hidden;border-radius:50%;border:1px solid rgba(0,234,255,.65);background:#071323;box-shadow:0 0 18px rgba(0,234,255,.38),0 0 32px rgba(0,110,255,.22);cursor:pointer;transition:.2s}.jaya-fab:hover{transform:scale(1.06);box-shadow:0 0 24px rgba(0,234,255,.55),0 0 40px rgba(0,110,255,.28)}.jaya-fab img{width:100%;height:100%;object-fit:cover}.jaya-fab:after{content:'JAYA';position:fixed;right:94px;bottom:41px;padding:6px 9px;border-radius:999px;background:rgba(2,10,20,.72);border:1px solid rgba(0,234,255,.25);color:#dffcff;font:700 10px Arial;letter-spacing:1.5px;white-space:nowrap}
  .jaya-panel{position:fixed;right:22px;bottom:100px;z-index:1000;width:min(370px,calc(100vw - 28px));height:min(520px,calc(100vh - 135px));display:none;flex-direction:column;overflow:hidden;border-radius:18px;border:1px solid rgba(0,234,255,.4);background:rgba(2,9,19,.88);backdrop-filter:blur(10px);box-shadow:0 18px 55px rgba(0,0,0,.58),0 0 30px rgba(0,234,255,.12)}.jaya-panel.open{display:flex}.jaya-head{display:flex;align-items:center;gap:10px;padding:14px 15px;border-bottom:1px solid rgba(0,234,255,.18);background:rgba(0,30,55,.35);flex:none}.jaya-avatar{width:40px;height:40px;border-radius:50%;overflow:hidden;border:1px solid rgba(0,234,255,.55);box-shadow:0 0 12px rgba(0,234,255,.22);flex:none}.jaya-avatar img{width:100%;height:100%;object-fit:cover}.jaya-title{flex:1}.jaya-title strong{display:block;color:#fff;font:800 14px Arial;letter-spacing:1px}.jaya-title span{display:block;margin-top:2px;color:#7fa3b8;font:11px Arial}.jaya-lang{max-width:86px;height:30px;border:1px solid rgba(0,234,255,.28);border-radius:999px;background:#071525;color:#dffcff;padding:0 7px;font:700 11px Arial;cursor:pointer;outline:none}.jaya-lang:focus{border-color:rgba(0,234,255,.7)}.jaya-close{border:0;background:none;color:#9bb1c1;font-size:24px;cursor:pointer}.jaya-messages{flex:1;min-height:0;overflow:auto;-webkit-overflow-scrolling:touch;padding:14px;display:flex;flex-direction:column;gap:10px}.jaya-msg{max-width:88%;padding:10px 12px;border-radius:13px;font:13px/1.45 Arial;white-space:pre-wrap}.jaya-msg.bot{align-self:flex-start;color:#dcebf4;background:rgba(0,126,180,.10);border:1px solid rgba(0,234,255,.17)}.jaya-msg.user{align-self:flex-end;color:#fff;background:rgba(0,105,220,.18);border:1px solid rgba(0,160,255,.25)}.jaya-form{display:flex;flex:none;gap:8px;padding:11px;padding-bottom:max(11px,env(safe-area-inset-bottom));border-top:1px solid rgba(0,234,255,.15);background:rgba(0,0,0,.14)}.jaya-input{min-width:0;flex:1;border:1px solid rgba(0,234,255,.28);border-radius:999px;background:rgba(0,0,0,.25);color:#fff;padding:11px 13px;outline:none;font:16px Arial}.jaya-input:focus{border-color:rgba(0,234,255,.65)}.jaya-send{width:42px;height:42px;flex:none;border-radius:50%;border:1px solid rgba(0,234,255,.5);background:rgba(0,150,220,.15);color:#fff;cursor:pointer;font-size:17px}.jaya-send:disabled{opacity:.45;cursor:default}
  .v2-studio-mic{position:fixed;z-index:8;right:-92px;top:205px;width:315px;height:auto;pointer-events:none;user-select:none;opacity:.78;filter:brightness(.76) saturate(.92) drop-shadow(0 0 18px rgba(0,180,255,.20));transform:rotate(-1deg);transform-origin:center right}.jaya-panel,.jaya-fab{z-index:1000}
  .v2-player{overflow:hidden!important;min-height:205px!important}.radio-live-row{display:flex;justify-content:center;align-items:center;gap:12px;margin-bottom:7px}.radio-live-badge{display:inline-flex;align-items:center;gap:6px;padding:5px 10px;border:1px solid rgba(0,234,255,.38);border-radius:999px;color:#fff;background:rgba(0,12,24,.35);font:800 10px Arial;letter-spacing:1.5px}.radio-live-dot{width:7px;height:7px;border-radius:50%;background:#00eaff;box-shadow:0 0 10px #00eaff;animation:radioPulse 1.15s ease-in-out infinite}.radio-vu-mini{height:18px;display:flex;align-items:center;gap:3px}.radio-vu-mini i{display:block;background:#00eaff;box-shadow:0 0 8px rgba(0,234,255,.72);transform-origin:center;animation:radioBar .58s ease-in-out infinite alternate;width:2px;border-radius:2px}.radio-vu-mini i:nth-child(1){height:6px}.radio-vu-mini i:nth-child(2){height:13px;animation-delay:.12s}.radio-vu-mini i:nth-child(3){height:9px;animation-delay:.28s}.radio-vu-mini i:nth-child(4){height:16px;animation-delay:.05s}.radio-vu-mini i:nth-child(5){height:8px;animation-delay:.35s}.radio-vu-mini i:nth-child(6){height:12px;animation-delay:.18s}.radio-wave{height:34px;margin:11px auto 7px;display:flex;justify-content:center;align-items:flex-end;gap:3px;opacity:.96}.radio-wave i{display:block;width:5px;height:30px;background:repeating-linear-gradient(to top,#00eaff 0 3px,transparent 3px 5px);filter:drop-shadow(0 0 3px rgba(0,234,255,.78));transform-origin:center bottom;animation:radioBargraph .48s steps(6,end) infinite alternate}.radio-wave i:nth-child(3n){animation-duration:.38s;animation-delay:.20s}.radio-wave i:nth-child(3n+1){animation-duration:.62s;animation-delay:.05s}.radio-wave i:nth-child(3n+2){animation-duration:.51s;animation-delay:.32s}.radio-wave i:nth-child(4n){animation-duration:.72s;animation-delay:.14s}.radio-wave i:nth-child(5n){animation-duration:.43s;animation-delay:.27s}.radio-genre{margin:5px 0 2px;color:#a8c7d8;font:700 9px Arial;letter-spacing:1.7px;text-transform:uppercase}.v2-play-button.radio-button{width:auto!important;height:44px!important;min-width:190px!important;padding:0 18px!important;border-radius:999px!important;margin-top:10px!important;display:inline-flex!important;gap:9px!important;font-size:11px!important;font-weight:800!important;letter-spacing:1.2px!important}.radio-button.playing{background:linear-gradient(135deg,rgba(0,234,255,.34),rgba(0,105,220,.22))!important}.radio-wave.paused i{animation-play-state:paused;opacity:.28;transform:scaleY(.12)}.radio-vu-mini.paused i{animation-play-state:paused;opacity:.35;transform:scaleY(.28)}@keyframes radioPulse{50%{opacity:.35;transform:scale(.75)}}@keyframes radioBar{0%{transform:scaleY(.18);opacity:.38}45%{transform:scaleY(.72);opacity:.8}100%{transform:scaleY(1.28);opacity:1}}@keyframes radioBargraph{0%{transform:scaleY(.16)}22%{transform:scaleY(.48)}45%{transform:scaleY(.82)}67%{transform:scaleY(.34)}82%{transform:scaleY(1)}100%{transform:scaleY(.62)}}
  @media(max-width:1100px){.v2-studio-mic{right:-115px;width:270px;opacity:.62}}@media(max-width:760px){.v2-studio-mic{display:none}}@media(max-width:600px){.jaya-fab{right:14px;bottom:14px;width:58px;height:58px}.jaya-fab:after{display:none}.jaya-panel{right:14px;bottom:82px;width:calc(100vw - 28px);height:min(500px,calc(100dvh - 105px))}.v2-player{min-height:210px!important}.radio-genre{font-size:8px;letter-spacing:1px}.v2-play-button.radio-button{min-width:175px!important}}
  `;
  const style=document.createElement('style');style.textContent=css;document.head.appendChild(style);

  const mic=document.createElement('img');mic.className='v2-studio-mic';mic.src='Micro-Technorizon-V2-Transparent.png';mic.alt='';mic.setAttribute('aria-hidden','true');document.body.appendChild(mic);

  const player=document.querySelector('.v2-player'),audio=document.getElementById('v2-audio'),playButton=document.getElementById('v2-play'),nowLabel=player?.querySelector('.v2-now-label'),artist=document.getElementById('v2-artist');
  if(player&&audio&&playButton&&nowLabel&&artist){
    nowLabel.style.display='none';
    const live=document.createElement('div');live.className='radio-live-row';live.innerHTML='<span class="radio-live-badge"><span class="radio-live-dot"></span><span class="radio-live-text">EN DIRECT</span></span><span class="radio-vu-mini paused" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i><i></i></span>';
    player.insertBefore(live,player.firstChild);
    const genre=document.createElement('div');genre.className='radio-genre';artist.insertAdjacentElement('afterend',genre);
    const wave=document.createElement('div');wave.className='radio-wave paused';wave.setAttribute('aria-hidden','true');wave.innerHTML='<i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i>';
    genre.insertAdjacentElement('afterend',wave);
    playButton.classList.add('radio-button');
    const setRadioState=()=>{const playing=!audio.paused,isEn=(localStorage.getItem('technorizon-lang')||'fr')==='en';playButton.textContent=playing?(isEn?'❚❚  NOW PLAYING':'❚❚  EN ÉCOUTE'):(isEn?'▶  LISTEN LIVE':'▶  ÉCOUTER LE DIRECT');live.querySelector('.radio-live-text').textContent=isEn?'LIVE':'EN DIRECT';genre.textContent=isEn?'TECHNO • EURODANCE • HOUSE • 90’S → TODAY':"TECHNO • EURODANCE • HOUSE • 90’S → AUJOURD’HUI";playButton.classList.toggle('playing',playing);wave.classList.toggle('paused',!playing);live.querySelector('.radio-vu-mini').classList.toggle('paused',!playing)};
    audio.addEventListener('playing',setRadioState);audio.addEventListener('pause',setRadioState);audio.addEventListener('ended',setRadioState);document.getElementById('lang-fr')?.addEventListener('click',()=>setTimeout(setRadioState,0));document.getElementById('lang-en')?.addEventListener('click',()=>setTimeout(setRadioState,0));setRadioState();
  }

  const jayaTexts={
    fr:{subtitle:'Assistante Technorizon',greeting:'Bonjour 👋 Je suis Jaya, l’assistante de Technorizon. Tu peux me parler naturellement ou me poser une question sur Technorizon, la musique ou la culture générale.',placeholder:'Pose ta question à Jaya…',open:'Ouvrir Jaya',close:'Fermer',send:'Envoyer',wait:'Jaya réfléchit…',waitLive:'Jaya vérifie le direct…',unknown:'Je n’ai pas encore la réponse à cette question. Essaie de me la reformuler 😊',connection:'Je rencontre un problème de connexion. Réessaie dans un instant.',live:'En ce moment sur Technorizon 🎵',liveFail:'Je n’arrive pas à lire le titre en cours pour le moment. Réessaie dans quelques secondes 😊'},
    en:{subtitle:'Technorizon Assistant',greeting:'Hello 👋 I’m Jaya, Technorizon’s assistant. You can chat with me naturally or ask me about Technorizon, music or general knowledge.',placeholder:'Ask Jaya a question…',open:'Open Jaya',close:'Close',send:'Send',wait:'Jaya is thinking…',waitLive:'Jaya is checking the live broadcast…',unknown:'I don’t have the answer yet. Try rephrasing your question 😊',connection:'I’m having a connection problem. Please try again in a moment.',live:'Now playing on Technorizon 🎵',liveFail:'I can’t read the current track right now. Please try again in a few seconds 😊'},
    es:{subtitle:'Asistente de Technorizon',greeting:'Hola 👋 Soy Jaya, la asistente de Technorizon. Puedes hablar conmigo o preguntarme sobre Technorizon, música o cultura general.',placeholder:'Hazle una pregunta a Jaya…',open:'Abrir Jaya',close:'Cerrar',send:'Enviar',wait:'Jaya está pensando…',waitLive:'Jaya consulta la emisión…',unknown:'Todavía no tengo la respuesta. Intenta reformular la pregunta 😊',connection:'Tengo un problema de conexión. Inténtalo de nuevo en un momento.',live:'Ahora en Technorizon 🎵',liveFail:'No puedo consultar la canción actual. Inténtalo de nuevo en unos segundos 😊'},
    de:{subtitle:'Technorizon-Assistentin',greeting:'Hallo 👋 Ich bin Jaya, die Assistentin von Technorizon. Du kannst mit mir sprechen oder mich zu Technorizon, Musik und Allgemeinwissen fragen.',placeholder:'Stelle Jaya eine Frage…',open:'Jaya öffnen',close:'Schließen',send:'Senden',wait:'Jaya denkt nach…',waitLive:'Jaya prüft das Liveprogramm…',unknown:'Darauf habe ich noch keine Antwort. Formuliere die Frage bitte anders 😊',connection:'Ich habe gerade ein Verbindungsproblem. Versuche es gleich noch einmal.',live:'Jetzt auf Technorizon 🎵',liveFail:'Ich kann den aktuellen Titel gerade nicht abrufen. Versuche es in wenigen Sekunden erneut 😊'},
    it:{subtitle:'Assistente Technorizon',greeting:'Ciao 👋 Sono Jaya, l’assistente di Technorizon. Puoi parlare con me o chiedermi di Technorizon, musica e cultura generale.',placeholder:'Fai una domanda a Jaya…',open:'Apri Jaya',close:'Chiudi',send:'Invia',wait:'Jaya sta pensando…',waitLive:'Jaya controlla la diretta…',unknown:'Non ho ancora la risposta. Prova a riformulare la domanda 😊',connection:'Ho un problema di connessione. Riprova tra poco.',live:'Ora su Technorizon 🎵',liveFail:'Non riesco a leggere il brano in onda. Riprova tra qualche secondo 😊'},
    nl:{subtitle:'Technorizon-assistente',greeting:'Hallo 👋 Ik ben Jaya, de assistente van Technorizon. Je kunt met me praten of vragen stellen over Technorizon, muziek en algemene kennis.',placeholder:'Stel Jaya een vraag…',open:'Jaya openen',close:'Sluiten',send:'Verzenden',wait:'Jaya denkt na…',waitLive:'Jaya controleert de live-uitzending…',unknown:'Ik heb het antwoord nog niet. Probeer je vraag anders te formuleren 😊',connection:'Ik heb een verbindingsprobleem. Probeer het zo opnieuw.',live:'Nu op Technorizon 🎵',liveFail:'Ik kan het huidige nummer niet ophalen. Probeer het over een paar seconden opnieuw 😊'},
    pt:{subtitle:'Assistente Technorizon',greeting:'Olá 👋 Sou a Jaya, assistente da Technorizon. Podes falar comigo ou perguntar sobre a Technorizon, música e cultura geral.',placeholder:'Faz uma pergunta à Jaya…',open:'Abrir Jaya',close:'Fechar',send:'Enviar',wait:'Jaya está a pensar…',waitLive:'Jaya verifica a emissão…',unknown:'Ainda não tenho essa resposta. Tenta reformular a pergunta 😊',connection:'Estou com um problema de ligação. Tenta novamente dentro de instantes.',live:'Agora na Technorizon 🎵',liveFail:'Não consigo consultar a música atual. Tenta novamente dentro de alguns segundos 😊'}
  };
  const supportedJayaLanguages=Object.keys(jayaTexts);
  let jayaLang=localStorage.getItem('technorizon-jaya-lang')||localStorage.getItem('technorizon-lang')||'fr';
  if(!supportedJayaLanguages.includes(jayaLang))jayaLang='fr';

  const fab=document.createElement('button');fab.className='jaya-fab';fab.type='button';fab.innerHTML=`<img src="${avatar}" alt="Jaya">`;
  const panel=document.createElement('section');panel.className='jaya-panel';panel.setAttribute('aria-label','Assistant Jaya');panel.innerHTML=`<div class="jaya-head"><div class="jaya-avatar"><img src="${avatar}" alt="Jaya"></div><div class="jaya-title"><strong>JAYA</strong><span class="jaya-subtitle"></span></div><select class="jaya-lang" aria-label="Langue de Jaya"><option value="fr">🇫🇷 FR</option><option value="en">🇬🇧 EN</option><option value="es">🇪🇸 ES</option><option value="de">🇩🇪 DE</option><option value="it">🇮🇹 IT</option><option value="nl">🇳🇱 NL</option><option value="pt">🇵🇹 PT</option></select><button class="jaya-close" type="button">×</button></div><div class="jaya-messages"><div class="jaya-msg bot jaya-greeting"></div></div><form class="jaya-form"><input class="jaya-input" type="text" maxlength="500" autocomplete="off"><button class="jaya-send" type="submit">➤</button></form>`;document.body.append(panel,fab);
  const close=panel.querySelector('.jaya-close'),form=panel.querySelector('.jaya-form'),input=panel.querySelector('.jaya-input'),send=panel.querySelector('.jaya-send'),messages=panel.querySelector('.jaya-messages'),langSelect=panel.querySelector('.jaya-lang'),subtitle=panel.querySelector('.jaya-subtitle'),greeting=panel.querySelector('.jaya-greeting');
  const applyJayaLanguage=(replaceGreeting=true)=>{const t=jayaTexts[jayaLang];langSelect.value=jayaLang;subtitle.textContent=t.subtitle;input.placeholder=t.placeholder;input.setAttribute('aria-label',t.placeholder);fab.setAttribute('aria-label',t.open);close.setAttribute('aria-label',t.close);send.setAttribute('aria-label',t.send);if(replaceGreeting&&messages.children.length===1)greeting.textContent=t.greeting};
  langSelect.addEventListener('change',()=>{jayaLang=langSelect.value;localStorage.setItem('technorizon-jaya-lang',jayaLang);applyJayaLanguage(true);input.focus()});
  applyJayaLanguage(true);

  const fitJayaToViewport=()=>{if(!panel.classList.contains('open')||window.innerWidth>600)return;const vv=window.visualViewport;if(!vv){panel.style.removeProperty('top');panel.style.removeProperty('bottom');panel.style.removeProperty('height');return}const keyboardOpen=(window.innerHeight-vv.height)>120;if(keyboardOpen){const top=Math.max(8,vv.offsetTop+8);const height=Math.max(220,vv.height-16);panel.style.top=`${top}px`;panel.style.bottom='auto';panel.style.height=`${height}px`}else{panel.style.removeProperty('top');panel.style.removeProperty('bottom');panel.style.removeProperty('height')}};
  if(window.visualViewport){window.visualViewport.addEventListener('resize',fitJayaToViewport);window.visualViewport.addEventListener('scroll',fitJayaToViewport)}
  input.addEventListener('focus',()=>setTimeout(fitJayaToViewport,120));input.addEventListener('blur',()=>setTimeout(fitJayaToViewport,120));

  const toggle=open=>{panel.classList.toggle('open',open);fab.setAttribute('aria-expanded',String(open));if(open){setTimeout(()=>{fitJayaToViewport();input.focus()},50)}else{panel.style.removeProperty('top');panel.style.removeProperty('bottom');panel.style.removeProperty('height')}};fab.onclick=()=>toggle(!panel.classList.contains('open'));close.onclick=()=>toggle(false);
  const conversation=[];const remember=(role,content)=>{conversation.push({role,content:String(content).slice(0,500)});if(conversation.length>6)conversation.splice(0,conversation.length-6)};const add=(text,who)=>{const el=document.createElement('div');el.className=`jaya-msg ${who}`;el.textContent=text;messages.appendChild(el);messages.scrollTop=messages.scrollHeight;return el};
  const clean=q=>q.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[!?.,;:'’]/g,' ').replace(/\s+/g,' ').trim();
  const smallTalk=q=>{if(jayaLang!=='fr')return null;const s=clean(q);if(/^(slt|salut|bjr|bonjour|bsr|bonsoir|cc|coucou|hello|hey)( |$)/.test(s)&&/(cv|ca va|comment vas tu|tu vas bien)/.test(s))return 'Salut 👋 Oui, ça va très bien, merci ! Et toi ? 😎';if(/^(slt|salut|bjr|bonjour|bsr|bonsoir|cc|coucou|hello|hey)$/.test(s))return 'Salut 👋 Ravie de te retrouver ! Comment vas-tu ? 😊';if(/^(cv|ca va|comment vas tu|tu vas bien|comment ca va)$/.test(s))return 'Très bien, merci 😊 Et toi, comment ça va ?';if(/^(oui|ouais|yes|yep|ca va|ca roule|nickel|super|tres bien|bien|tranquille)( merci)?$/.test(s))return 'Super 😎 Ça fait plaisir ! Je suis là si tu veux parler musique ou Technorizon.';if(/^(non|bof|pas trop|pas bien|ca va pas|ca ne va pas)$/.test(s))return 'Ah mince 😕 J’espère que ça ira vite mieux. Je peux au moins te tenir compagnie un moment 😊';if(/^(ok|okay|d accord|dac|dacc|ca marche|entendu)$/.test(s))return 'Ça marche 😊';if(/^(merci|merci beaucoup|mercii+|thx|thanks)$/.test(s)||/^(d accord|ok|super|parfait|nickel) merci( beaucoup)?$/.test(s))return 'Avec plaisir 😊 Bonne écoute sur Technorizon !';if(/^(de rien|avec plaisir)$/.test(s))return '😊';if(/^(mdr|lol|😂|🤣)$/.test(s))return '🤣 Tu me fais rire !';if(/^(au revoir|a bientot|a plus|a\+|bonne journee|bonne soiree|bonne nuit|bye|ciao)$/.test(s))return 'À bientôt 👋 Et bonne écoute sur Technorizon !';if(/qui es tu|presente toi|tu es qui|c est quoi jaya/.test(s))return 'Je suis Jaya, l’assistante virtuelle de Technorizon 🤖🎵 Je peux discuter avec toi et répondre à tes questions sur la radio, les artistes, les titres et ce qui passe à l’antenne.';return null};
  const liveQuestion=q=>{const s=clean(q);return /(quel|quelle|quoi|titre|musique|morceau|chanson|artiste).*(passe|diffuse|joue|ecoute|antenne|moment|maintenant|actuel)|en ce moment/.test(s)};
  const getLive=async()=>{const t=jayaTexts[jayaLang];try{const r=await fetch('/api/nowplaying/technorizon',{cache:'no-store'});if(!r.ok)throw Error();const d=await r.json(),song=d?.now_playing?.song||{};if(song.title){const artist=song.artist?` — ${song.artist}`:'';return `${t.live} ${song.title}${artist}. 😎`}}catch(e){}return t.liveFail};
  form.addEventListener('submit',async e=>{e.preventDefault();const question=input.value.trim();if(!question)return;add(question,'user');remember('user',question);input.value='';const local=smallTalk(question);if(local){add(local,'bot');remember('assistant',local);input.focus();return}if(liveQuestion(question)){send.disabled=true;const wait=add(jayaTexts[jayaLang].waitLive,'bot');wait.textContent=await getLive();remember('assistant',wait.textContent);send.disabled=false;input.focus();return}send.disabled=true;const wait=add(jayaTexts[jayaLang].wait,'bot');try{const r=await fetch('/api/jaya-brain',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question,language:jayaLang,history:conversation.slice(0,-1)})});const d=await r.json();wait.textContent=d.answer||d.error||jayaTexts[jayaLang].unknown;remember('assistant',wait.textContent)}catch(err){wait.textContent=jayaTexts[jayaLang].connection;remember('assistant',wait.textContent)}finally{send.disabled=false;input.focus();messages.scrollTop=messages.scrollHeight}});
})();