(() => {
  const css = `
  .jaya-fab{position:fixed;right:22px;bottom:22px;z-index:1000;width:66px;height:66px;border-radius:50%;border:1px solid rgba(0,234,255,.65);background:radial-gradient(circle at 35% 30%,#173b5e 0%,#071323 55%,#02060d 100%);color:#fff;box-shadow:0 0 18px rgba(0,234,255,.38),0 0 32px rgba(0,110,255,.22);cursor:pointer;font:800 26px Arial;display:grid;place-items:center;transition:.2s}.jaya-fab:hover{transform:scale(1.06);box-shadow:0 0 24px rgba(0,234,255,.55),0 0 40px rgba(0,110,255,.28)}
  .jaya-fab:after{content:'JAYA';position:absolute;right:72px;padding:6px 9px;border-radius:999px;background:rgba(2,10,20,.82);border:1px solid rgba(0,234,255,.25);color:#dffcff;font:700 10px Arial;letter-spacing:1.5px;white-space:nowrap}
  .jaya-panel{position:fixed;right:22px;bottom:100px;z-index:1000;width:min(370px,calc(100vw - 28px));height:min(520px,calc(100vh - 135px));display:none;flex-direction:column;overflow:hidden;border-radius:18px;border:1px solid rgba(0,234,255,.4);background:rgba(2,9,19,.94);backdrop-filter:blur(14px);box-shadow:0 18px 55px rgba(0,0,0,.58),0 0 30px rgba(0,234,255,.12)}.jaya-panel.open{display:flex}
  .jaya-head{display:flex;align-items:center;gap:10px;padding:14px 15px;border-bottom:1px solid rgba(0,234,255,.18);background:linear-gradient(90deg,rgba(0,234,255,.09),rgba(0,80,180,.08))}.jaya-avatar{width:38px;height:38px;border-radius:50%;display:grid;place-items:center;border:1px solid rgba(0,234,255,.55);color:#fff;font:800 18px Arial;box-shadow:0 0 12px rgba(0,234,255,.22)}.jaya-title{flex:1}.jaya-title strong{display:block;color:#fff;font:800 14px Arial;letter-spacing:1px}.jaya-title span{display:block;margin-top:2px;color:#7fa3b8;font:11px Arial}.jaya-close{border:0;background:none;color:#9bb1c1;font-size:24px;cursor:pointer}
  .jaya-messages{flex:1;overflow:auto;padding:14px;display:flex;flex-direction:column;gap:10px}.jaya-msg{max-width:88%;padding:10px 12px;border-radius:13px;font:13px/1.45 Arial;white-space:pre-wrap}.jaya-msg.bot{align-self:flex-start;color:#dcebf4;background:rgba(0,126,180,.13);border:1px solid rgba(0,234,255,.17)}.jaya-msg.user{align-self:flex-end;color:#fff;background:rgba(0,105,220,.22);border:1px solid rgba(0,160,255,.25)}
  .jaya-form{display:flex;gap:8px;padding:11px;border-top:1px solid rgba(0,234,255,.15);background:rgba(0,0,0,.18)}.jaya-input{min-width:0;flex:1;border:1px solid rgba(0,234,255,.22);border-radius:999px;background:rgba(0,0,0,.35);color:#fff;padding:11px 13px;outline:none;font:13px Arial}.jaya-input:focus{border-color:rgba(0,234,255,.55)}.jaya-send{width:42px;height:42px;border-radius:50%;border:1px solid rgba(0,234,255,.5);background:rgba(0,150,220,.18);color:#fff;cursor:pointer;font-size:17px}.jaya-send:disabled{opacity:.45;cursor:default}
  @media(max-width:600px){.jaya-fab{right:14px;bottom:14px;width:58px;height:58px}.jaya-fab:after{display:none}.jaya-panel{right:14px;bottom:82px;width:calc(100vw - 28px);height:min(500px,calc(100vh - 105px))}}
  `;
  const style=document.createElement('style'); style.textContent=css; document.head.appendChild(style);
  const fab=document.createElement('button'); fab.className='jaya-fab'; fab.type='button'; fab.setAttribute('aria-label','Ouvrir Jaya'); fab.textContent='J';
  const panel=document.createElement('section'); panel.className='jaya-panel'; panel.setAttribute('aria-label','Assistant Jaya');
  panel.innerHTML=`<div class="jaya-head"><div class="jaya-avatar">J</div><div class="jaya-title"><strong>JAYA</strong><span>Assistante Technorizon</span></div><button class="jaya-close" type="button" aria-label="Fermer">×</button></div><div class="jaya-messages"><div class="jaya-msg bot">Bonjour 👋 Je suis Jaya. Pose-moi une question sur Technorizon, ses artistes ou ses titres.</div></div><form class="jaya-form"><input class="jaya-input" type="text" maxlength="500" autocomplete="off" placeholder="Pose ta question à Jaya…" aria-label="Question à Jaya"><button class="jaya-send" type="submit" aria-label="Envoyer">➤</button></form>`;
  document.body.append(panel,fab);
  const close=panel.querySelector('.jaya-close'),form=panel.querySelector('.jaya-form'),input=panel.querySelector('.jaya-input'),send=panel.querySelector('.jaya-send'),messages=panel.querySelector('.jaya-messages');
  const toggle=(open)=>{panel.classList.toggle('open',open);fab.setAttribute('aria-expanded',String(open));if(open)setTimeout(()=>input.focus(),50)};
  fab.addEventListener('click',()=>toggle(!panel.classList.contains('open'))); close.addEventListener('click',()=>toggle(false));
  const add=(text,who)=>{const el=document.createElement('div');el.className=`jaya-msg ${who}`;el.textContent=text;messages.appendChild(el);messages.scrollTop=messages.scrollHeight;return el};
  form.addEventListener('submit',async(e)=>{e.preventDefault();const question=input.value.trim();if(!question)return;add(question,'user');input.value='';send.disabled=true;const wait=add('Jaya réfléchit…','bot');try{const r=await fetch('/api/jaya-brain',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question})});const d=await r.json();wait.textContent=d.answer||d.error||'Je n’ai pas trouvé de réponse pour le moment.'}catch(err){wait.textContent='Je rencontre un problème de connexion. Réessaie dans un instant.'}finally{send.disabled=false;input.focus();messages.scrollTop=messages.scrollHeight}});
})();