(() => {
  const avatar='JayaV2.jpg';
  const css=`
  .jaya-fab{position:fixed;right:22px;bottom:22px;z-index:1000;width:66px;height:66px;padding:0;overflow:hidden;border-radius:50%;border:1px solid rgba(0,234,255,.65);background:#071323;box-shadow:0 0 18px rgba(0,234,255,.38),0 0 32px rgba(0,110,255,.22);cursor:pointer;transition:.2s}.jaya-fab:hover{transform:scale(1.06);box-shadow:0 0 24px rgba(0,234,255,.55),0 0 40px rgba(0,110,255,.28)}.jaya-fab img{width:100%;height:100%;object-fit:cover}.jaya-fab:after{content:'JAYA';position:fixed;right:94px;bottom:41px;padding:6px 9px;border-radius:999px;background:rgba(2,10,20,.72);border:1px solid rgba(0,234,255,.25);color:#dffcff;font:700 10px Arial;letter-spacing:1.5px;white-space:nowrap}
  .jaya-panel{position:fixed;right:22px;bottom:100px;z-index:1000;width:min(370px,calc(100vw - 28px));height:min(520px,calc(100vh - 135px));display:none;flex-direction:column;overflow:hidden;border-radius:18px;border:1px solid rgba(0,234,255,.4);background:rgba(2,9,19,.88);backdrop-filter:blur(10px);box-shadow:0 18px 55px rgba(0,0,0,.58),0 0 30px rgba(0,234,255,.12)}.jaya-panel.open{display:flex}.jaya-head{display:flex;align-items:center;gap:10px;padding:14px 15px;border-bottom:1px solid rgba(0,234,255,.18);background:rgba(0,30,55,.35)}.jaya-avatar{width:40px;height:40px;border-radius:50%;overflow:hidden;border:1px solid rgba(0,234,255,.55);box-shadow:0 0 12px rgba(0,234,255,.22);flex:none}.jaya-avatar img{width:100%;height:100%;object-fit:cover}.jaya-title{flex:1}.jaya-title strong{display:block;color:#fff;font:800 14px Arial;letter-spacing:1px}.jaya-title span{display:block;margin-top:2px;color:#7fa3b8;font:11px Arial}.jaya-close{border:0;background:none;color:#9bb1c1;font-size:24px;cursor:pointer}.jaya-messages{flex:1;overflow:auto;padding:14px;display:flex;flex-direction:column;gap:10px}.jaya-msg{max-width:88%;padding:10px 12px;border-radius:13px;font:13px/1.45 Arial;white-space:pre-wrap}.jaya-msg.bot{align-self:flex-start;color:#dcebf4;background:rgba(0,126,180,.10);border:1px solid rgba(0,234,255,.17)}.jaya-msg.user{align-self:flex-end;color:#fff;background:rgba(0,105,220,.18);border:1px solid rgba(0,160,255,.25)}.jaya-form{display:flex;gap:8px;padding:11px;border-top:1px solid rgba(0,234,255,.15);background:rgba(0,0,0,.14)}.jaya-input{min-width:0;flex:1;border:1px solid rgba(0,234,255,.28);border-radius:999px;background:rgba(0,0,0,.25);color:#fff;padding:11px 13px;outline:none;font:13px Arial}.jaya-input:focus{border-color:rgba(0,234,255,.65)}.jaya-send{width:42px;height:42px;border-radius:50%;border:1px solid rgba(0,234,255,.5);background:rgba(0,150,220,.15);color:#fff;cursor:pointer;font-size:17px}.jaya-send:disabled{opacity:.45;cursor:default}@media(max-width:600px){.jaya-fab{right:14px;bottom:14px;width:58px;height:58px}.jaya-fab:after{display:none}.jaya-panel{right:14px;bottom:82px;width:calc(100vw - 28px);height:min(500px,calc(100vh - 105px))}}
  `;
  const style=document.createElement('style');style.textContent=css;document.head.appendChild(style);
  const fab=document.createElement('button');fab.className='jaya-fab';fab.type='button';fab.setAttribute('aria-label','Ouvrir Jaya');fab.innerHTML=`<img src="${avatar}" alt="Jaya">`;
  const panel=document.createElement('section');panel.className='jaya-panel';panel.setAttribute('aria-label','Assistant Jaya');panel.innerHTML=`<div class="jaya-head"><div class="jaya-avatar"><img src="${avatar}" alt="Jaya"></div><div class="jaya-title"><strong>JAYA</strong><span>Assistante Technorizon</span></div><button class="jaya-close" type="button" aria-label="Fermer">×</button></div><div class="jaya-messages"><div class="jaya-msg bot">Bonjour 👋 Je suis Jaya, l’assistante de Technorizon. Tu peux me parler naturellement ou me poser une question sur Technorizon, ses artistes et ses titres.</div></div><form class="jaya-form"><input class="jaya-input" type="text" maxlength="500" autocomplete="off" placeholder="Pose ta question à Jaya…" aria-label="Question à Jaya"><button class="jaya-send" type="submit" aria-label="Envoyer">➤</button></form>`;document.body.append(panel,fab);
  const close=panel.querySelector('.jaya-close'),form=panel.querySelector('.jaya-form'),input=panel.querySelector('.jaya-input'),send=panel.querySelector('.jaya-send'),messages=panel.querySelector('.jaya-messages');
  const toggle=open=>{panel.classList.toggle('open',open);fab.setAttribute('aria-expanded',String(open));if(open)setTimeout(()=>input.focus(),50)};fab.onclick=()=>toggle(!panel.classList.contains('open'));close.onclick=()=>toggle(false);
  const add=(text,who)=>{const el=document.createElement('div');el.className=`jaya-msg ${who}`;el.textContent=text;messages.appendChild(el);messages.scrollTop=messages.scrollHeight;return el};
  const clean=q=>q.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[!?.,;:'’]/g,' ').replace(/\s+/g,' ').trim();
  const smallTalk=q=>{const s=clean(q);
    if(/^(slt|salut|bjr|bonjour|bsr|bonsoir|cc|coucou|hello|hey)( |$)/.test(s)&&/(cv|ca va|comment vas tu|tu vas bien)/.test(s))return 'Salut 👋 Oui, ça va très bien, merci ! Et toi ? 😎';
    if(/^(slt|salut|bjr|bonjour|bsr|bonsoir|cc|coucou|hello|hey)$/.test(s))return 'Salut 👋 Ravie de te retrouver ! Comment vas-tu ? 😊';
    if(/^(cv|ca va|comment vas tu|tu vas bien|comment ca va)$/.test(s))return 'Très bien, merci 😊 Et toi, comment ça va ?';
    if(/^(oui|ouais|yes|yep|ca va|ca roule|nickel|super|tres bien|bien|tranquille)( merci)?$/.test(s))return 'Super 😎 Ça fait plaisir ! Je suis là si tu veux parler musique ou Technorizon.';
    if(/^(non|bof|pas trop|pas bien|ca va pas|ca ne va pas)$/.test(s))return 'Ah mince 😕 J’espère que ça ira vite mieux. Je peux au moins te tenir compagnie un moment 😊';
    if(/^(ok|okay|d accord|dac|dacc|ca marche|entendu)$/.test(s))return 'Ça marche 😊';
    if(/^(merci|merci beaucoup|mercii+|thx|thanks)$/.test(s)||/^(d accord|ok|super|parfait|nickel) merci( beaucoup)?$/.test(s))return 'Avec plaisir 😊 Bonne écoute sur Technorizon !';
    if(/^(de rien|avec plaisir)$/.test(s))return '😊';
    if(/^(mdr|lol|😂|🤣)$/.test(s))return '🤣 Tu me fais rire !';
    if(/^(au revoir|a bientot|a plus|a\+|bonne journee|bonne soiree|bonne nuit|bye|ciao)$/.test(s))return 'À bientôt 👋 Et bonne écoute sur Technorizon !';
    if(/qui es tu|presente toi|tu es qui|c est quoi jaya/.test(s))return 'Je suis Jaya, l’assistante virtuelle de Technorizon 🤖🎵 Je peux discuter avec toi et répondre à tes questions sur la radio, les artistes, les titres et ce qui passe à l’antenne.';
    return null};
  const liveQuestion=q=>{const s=clean(q);return /(quel|quelle|quoi|titre|musique|morceau|chanson|artiste).*(passe|diffuse|joue|ecoute|antenne|moment|maintenant|actuel)|en ce moment/.test(s)};
  const getLive=async()=>{try{const r=await fetch('/api/nowplaying/technorizon',{cache:'no-store'});if(!r.ok)throw Error();const d=await r.json(),song=d?.now_playing?.song||{};if(song.title){const artist=song.artist?` par ${song.artist}`:'';return `En ce moment sur Technorizon 🎵 ${song.title}${artist}. 😎`}}catch(e){}return 'Je n’arrive pas à lire le titre en cours pour le moment. Réessaie dans quelques secondes 😊'};
  form.addEventListener('submit',async e=>{e.preventDefault();const question=input.value.trim();if(!question)return;add(question,'user');input.value='';const local=smallTalk(question);if(local){add(local,'bot');input.focus();return}if(liveQuestion(question)){send.disabled=true;const wait=add('Jaya vérifie le direct…','bot');wait.textContent=await getLive();send.disabled=false;input.focus();return}send.disabled=true;const wait=add('Jaya réfléchit…','bot');try{const r=await fetch('/api/jaya-brain',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question})});const d=await r.json();wait.textContent=d.answer||d.error||'Je n’ai pas encore la réponse à cette question. Essaie de me la reformuler 😊'}catch(err){wait.textContent='Je rencontre un problème de connexion. Réessaie dans un instant.'}finally{send.disabled=false;input.focus();messages.scrollTop=messages.scrollHeight}});
})();