const translations={
  fr:{back:"← Retour à l'accueil",title:'MÉTÉO',pageTitle:'Météo',sub:"Recherchez une ville dans le monde • Aujourd'hui et les prochains jours",ph:'Ville, ex. Rouen, Londres, New York…',search:'RECHERCHER',loading:'Chargement de la météo…',feel:'Ressenti',humidity:'Humidité',wind:'Vent',rain:'Pluie',today:"Aujourd’hui",error:'Les données météo sont momentanément indisponibles.',find:'Recherche de la ville…',notfound:'Ville introuvable.',france:'France'},
  en:{back:'← Back to home',title:'WEATHER',pageTitle:'Weather',sub:'Search for a city worldwide • Today and the next few days',ph:'City, e.g. Rouen, London, New York…',search:'SEARCH',loading:'Loading weather…',feel:'Feels like',humidity:'Humidity',wind:'Wind',rain:'Rain',today:'Today',error:'Weather data is temporarily unavailable.',find:'Searching for the city…',notfound:'City not found.',france:'France'},
  es:{back:'← Volver al inicio',title:'EL TIEMPO',pageTitle:'El tiempo',sub:'Busca una ciudad del mundo • Hoy y los próximos días',ph:'Ciudad, p. ej. Madrid, Londres, Nueva York…',search:'BUSCAR',loading:'Cargando el tiempo…',feel:'Sensación',humidity:'Humedad',wind:'Viento',rain:'Lluvia',today:'Hoy',error:'Los datos meteorológicos no están disponibles temporalmente.',find:'Buscando la ciudad…',notfound:'Ciudad no encontrada.',france:'Francia'},
  de:{back:'← Zurück zur Startseite',title:'WETTER',pageTitle:'Wetter',sub:'Suche weltweit nach einer Stadt • Heute und die nächsten Tage',ph:'Stadt, z. B. Berlin, London, New York…',search:'SUCHEN',loading:'Wetter wird geladen…',feel:'Gefühlt',humidity:'Luftfeuchtigkeit',wind:'Wind',rain:'Regen',today:'Heute',error:'Die Wetterdaten sind vorübergehend nicht verfügbar.',find:'Stadt wird gesucht…',notfound:'Stadt nicht gefunden.',france:'Frankreich'},
  it:{back:'← Torna alla home',title:'METEO',pageTitle:'Meteo',sub:'Cerca una città nel mondo • Oggi e i prossimi giorni',ph:'Città, es. Roma, Londra, New York…',search:'CERCA',loading:'Caricamento del meteo…',feel:'Percepita',humidity:'Umidità',wind:'Vento',rain:'Pioggia',today:'Oggi',error:'I dati meteo non sono temporaneamente disponibili.',find:'Ricerca della città…',notfound:'Città non trovata.',france:'Francia'},
  pt:{back:'← Voltar ao início',title:'METEOROLOGIA',pageTitle:'Meteorologia',sub:'Procura uma cidade no mundo • Hoje e nos próximos dias',ph:'Cidade, ex. Lisboa, Londres, Nova Iorque…',search:'PROCURAR',loading:'A carregar a meteorologia…',feel:'Sensação',humidity:'Humidade',wind:'Vento',rain:'Chuva',today:'Hoje',error:'Os dados meteorológicos estão temporariamente indisponíveis.',find:'A procurar a cidade…',notfound:'Cidade não encontrada.',france:'França'},
  nl:{back:'← Terug naar home',title:'WEER',pageTitle:'Weer',sub:'Zoek een stad wereldwijd • Vandaag en de komende dagen',ph:'Stad, bijv. Amsterdam, Londen, New York…',search:'ZOEKEN',loading:'Weer laden…',feel:'Gevoelstemperatuur',humidity:'Luchtvochtigheid',wind:'Wind',rain:'Regen',today:'Vandaag',error:'De weergegevens zijn tijdelijk niet beschikbaar.',find:'Stad zoeken…',notfound:'Stad niet gevonden.',france:'Frankrijk'}
};

const regionLanguages={fr:{lang:'fr',locale:'fr-FR'},be:{lang:'fr',locale:'fr-BE'},ch:{lang:'fr',locale:'fr-CH'},gb:{lang:'en',locale:'en-GB'},us:{lang:'en',locale:'en-US'},ca:{lang:'fr',locale:'fr-CA'},de:{lang:'de',locale:'de-DE'},es:{lang:'es',locale:'es-ES'},it:{lang:'it',locale:'it-IT'},pt:{lang:'pt',locale:'pt-PT'},nl:{lang:'nl',locale:'nl-NL'}};
const supportedRegions=Object.keys(regionLanguages);
const icons={0:'☀️',1:'🌤️',2:'⛅',3:'☁️',45:'☁️',48:'☁️',51:'🌦️',53:'🌦️',55:'🌧️',56:'🌧️',57:'🌧️',61:'🌧️',63:'🌧️',65:'🌧️',66:'🌧️',67:'🌧️',71:'🌨️',73:'🌨️',75:'❄️',77:'🌨️',80:'🌦️',81:'🌦️',82:'🌧️',85:'🌨️',86:'❄️',95:'⛈️',96:'⛈️',99:'⛈️'};
const conditions={
  fr:{0:'Ciel dégagé',1:'Peu nuageux',2:'Partiellement nuageux',3:'Couvert',45:'Brouillard',48:'Brouillard givrant',51:'Bruine faible',53:'Bruine',55:'Forte bruine',61:'Pluie faible',63:'Pluie',65:'Forte pluie',71:'Neige faible',73:'Neige',75:'Forte neige',80:'Averses faibles',81:'Averses',82:'Fortes averses',95:'Orage',96:'Orage avec grêle',99:'Fort orage avec grêle',fallback:'Variable'},
  en:{0:'Clear sky',1:'Mostly clear',2:'Partly cloudy',3:'Overcast',45:'Fog',48:'Freezing fog',51:'Light drizzle',53:'Drizzle',55:'Heavy drizzle',61:'Light rain',63:'Rain',65:'Heavy rain',71:'Light snow',73:'Snow',75:'Heavy snow',80:'Light showers',81:'Showers',82:'Heavy showers',95:'Thunderstorm',96:'Thunderstorm with hail',99:'Heavy thunderstorm with hail',fallback:'Variable'},
  es:{0:'Cielo despejado',1:'Poco nuboso',2:'Parcialmente nuboso',3:'Cubierto',45:'Niebla',48:'Niebla helada',51:'Llovizna ligera',53:'Llovizna',55:'Llovizna intensa',61:'Lluvia ligera',63:'Lluvia',65:'Lluvia intensa',71:'Nieve ligera',73:'Nieve',75:'Nieve intensa',80:'Chubascos ligeros',81:'Chubascos',82:'Chubascos intensos',95:'Tormenta',96:'Tormenta con granizo',99:'Tormenta fuerte con granizo',fallback:'Variable'},
  de:{0:'Klarer Himmel',1:'Überwiegend klar',2:'Teilweise bewölkt',3:'Bedeckt',45:'Nebel',48:'Gefrierender Nebel',51:'Leichter Nieselregen',53:'Nieselregen',55:'Starker Nieselregen',61:'Leichter Regen',63:'Regen',65:'Starker Regen',71:'Leichter Schneefall',73:'Schnee',75:'Starker Schneefall',80:'Leichte Schauer',81:'Regenschauer',82:'Starke Regenschauer',95:'Gewitter',96:'Gewitter mit Hagel',99:'Starkes Gewitter mit Hagel',fallback:'Wechselhaft'},
  it:{0:'Cielo sereno',1:'Prevalentemente sereno',2:'Parzialmente nuvoloso',3:'Coperto',45:'Nebbia',48:'Nebbia gelata',51:'Pioviggine leggera',53:'Pioviggine',55:'Pioviggine intensa',61:'Pioggia leggera',63:'Pioggia',65:'Pioggia intensa',71:'Neve leggera',73:'Neve',75:'Neve intensa',80:'Rovesci leggeri',81:'Rovesci',82:'Rovesci intensi',95:'Temporale',96:'Temporale con grandine',99:'Forte temporale con grandine',fallback:'Variabile'},
  pt:{0:'Céu limpo',1:'Pouco nublado',2:'Parcialmente nublado',3:'Encoberto',45:'Nevoeiro',48:'Nevoeiro gelado',51:'Chuvisco fraco',53:'Chuvisco',55:'Chuvisco forte',61:'Chuva fraca',63:'Chuva',65:'Chuva forte',71:'Neve fraca',73:'Neve',75:'Neve forte',80:'Aguaceiros fracos',81:'Aguaceiros',82:'Aguaceiros fortes',95:'Trovoada',96:'Trovoada com granizo',99:'Trovoada forte com granizo',fallback:'Variável'},
  nl:{0:'Heldere hemel',1:'Overwegend helder',2:'Gedeeltelijk bewolkt',3:'Bewolkt',45:'Mist',48:'Aanvriezende mist',51:'Lichte motregen',53:'Motregen',55:'Zware motregen',61:'Lichte regen',63:'Regen',65:'Zware regen',71:'Lichte sneeuw',73:'Sneeuw',75:'Zware sneeuw',80:'Lichte buien',81:'Buien',82:'Zware buien',95:'Onweer',96:'Onweer met hagel',99:'Zwaar onweer met hagel',fallback:'Wisselvallig'}
};

const out=document.getElementById('weather');
const form=document.getElementById('weatherSearch');
const input=document.getElementById('cityInput');
const savedRegion=localStorage.getItem('technorizon-weather-region')||localStorage.getItem('technorizon-jaya-region')||localStorage.getItem('technorizon-lang');
const migratedRegion=savedRegion==='en'?'gb':savedRegion;
let region=supportedRegions.includes(migratedRegion)?migratedRegion:'fr';
let lang=regionLanguages[region].lang;
let current={lat:49.6684,lon:0.8955,name:'Yerville',country:'France',countryCode:'FR',timezone:'Europe/Paris'};

function copy(){return translations[lang]}
function render(){const text=copy(),locale=regionLanguages[region].locale;document.documentElement.lang=locale;weatherLanguage.value=region;back.textContent=text.back;title.textContent=text.title;sub.textContent=text.sub;input.placeholder=text.ph;searchBtn.textContent=text.search;document.title=text.pageTitle+' | Technorizon.fr'}
function setRegion(nextRegion){region=supportedRegions.includes(nextRegion)?nextRegion:'fr';lang=regionLanguages[region].lang;localStorage.setItem('technorizon-weather-region',region);render();load()}
function condition(code){return conditions[lang][code]||conditions[lang].fallback}
function icon(code){return icons[code]||'☁️'}

async function load(){const text=copy(),locale=regionLanguages[region].locale;out.innerHTML=`<div class="status">${text.loading}</div>`;try{const url=`https://api.open-meteo.com/v1/forecast?latitude=${current.lat}&longitude=${current.lon}&current=temperature_2m,apparent_temperature,weather_code,wind_speed_10m,relative_humidity_2m&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max&timezone=${encodeURIComponent(current.timezone||'auto')}&forecast_days=5`;const response=await fetch(url,{cache:'no-store'});if(!response.ok)throw Error();const data=await response.json(),now=data.current,daily=data.daily;const country=current.countryCode==='FR'?text.france:current.country;weatherLocation.textContent=`📍 ${current.name}${country?', '+country:''}`;const cards=daily.time.map((date,index)=>`<div class="day"><div class="dayname">${index===0?text.today:new Intl.DateTimeFormat(locale,{weekday:'short'}).format(new Date(date+'T12:00:00'))}</div><div class="icon">${icon(daily.weather_code[index])}</div><div class="daytemp">${Math.round(daily.temperature_2m_min[index])}° / ${Math.round(daily.temperature_2m_max[index])}°</div><div class="extra">${text.rain} ${daily.precipitation_probability_max[index]??0}%</div></div>`).join('');out.innerHTML=`<div class="now"><div class="temp">${Math.round(now.temperature_2m)}°C</div><div class="condition">${icon(now.weather_code)} ${condition(now.weather_code)}</div><div class="extra">${text.feel} ${Math.round(now.apparent_temperature)}°C • ${text.humidity} ${now.relative_humidity_2m}% • ${text.wind} ${Math.round(now.wind_speed_10m)} km/h</div></div><div class="forecast">${cards}</div>`}catch(error){out.innerHTML=`<div class="status">${text.error}</div>`}}
async function searchCity(query){const text=copy();out.innerHTML=`<div class="status">${text.find}</div>`;try{const response=await fetch(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(query)}&count=1&language=${lang}&format=json`,{cache:'no-store'});if(!response.ok)throw Error();const data=await response.json(),place=data?.results?.[0];if(!place){out.innerHTML=`<div class="status">${text.notfound}</div>`;return}current={lat:place.latitude,lon:place.longitude,name:place.name,country:place.country||'',countryCode:place.country_code||'',timezone:place.timezone||'auto'};localStorage.setItem('technorizon-weather-location',JSON.stringify(current));load()}catch(error){out.innerHTML=`<div class="status">${text.error}</div>`}}

weatherLanguage.addEventListener('change',event=>setRegion(event.target.value));
form.addEventListener('submit',event=>{event.preventDefault();if(input.value.trim())searchCity(input.value.trim())});
try{const savedLocation=JSON.parse(localStorage.getItem('technorizon-weather-location'));if(savedLocation?.lat&&savedLocation?.lon)current=savedLocation}catch(error){}
render();load();setInterval(load,600000);
