(()=>{
'use strict';
const link=document.querySelector('a[href="meteo.html"].v2-card-link');if(!link)return;
const RL={fr:['fr','fr-FR'],be:['fr','fr-BE'],ch:['fr','fr-CH'],gb:['en','en-GB'],us:['en','en-US'],ca:['fr','fr-CA'],de:['de','de-DE'],es:['es','es-ES'],it:['it','it-IT'],pt:['pt','pt-PT'],nl:['nl','nl-NL']};
const T={fr:["← Retour à l’accueil",'MÉTÉO','Recherchez une ville dans le monde • Aujourd’hui et les prochains jours','Ville, ex. Rouen, Londres, New York…','RECHERCHER','Chargement de la météo…','Ressenti','Humidité','Vent','Pluie','Aujourd’hui','Données météo momentanément indisponibles.','Ville introuvable.'],en:['← Back to home','WEATHER','Search for a city worldwide • Today and the next few days','City, e.g. London, New York…','SEARCH','Loading weather…','Feels like','Humidity','Wind','Rain','Today','Weather data is temporarily unavailable.','City not found.'],de:['← Zurück zur Startseite','WETTER','Suche weltweit nach einer Stadt • Heute und die nächsten Tage','Stadt, z. B. Berlin, London…','SUCHEN','Wetter wird geladen…','Gefühlt','Luftfeuchtigkeit','Wind','Regen','Heute','Wetterdaten vorübergehend nicht verfügbar.','Stadt nicht gefunden.'],es:['← Volver al inicio','EL TIEMPO','Busca una ciudad del mundo • Hoy y los próximos días','Ciudad, p. ej. Madrid, Londres…','BUSCAR','Cargando el tiempo…','Sensación','Humedad','Viento','Lluvia','Hoy','Datos meteorológicos no disponibles.','Ciudad no encontrada.'],it:['← Torna alla home','METEO','Cerca una città nel mondo • Oggi e i prossimi giorni','Città, es. Roma, Londra…','CERCA','Caricamento meteo…','Percepita','Umidità','Vento','Pioggia','Oggi','Dati meteo non disponibili.','Città non trovata.'],pt:['← Voltar ao início','METEOROLOGIA','Procura uma cidade no mundo • Hoje e nos próximos dias','Cidade, ex. Lisboa, Londres…','PROCURAR','A carregar meteorologia…','Sensação','Humidade','Vento','Chuva','Hoje','Dados meteorológicos indisponíveis.','Cidade não encontrada.'],nl:['← Terug naar home','WEER','Zoek een stad wereldwijd • Vandaag en de komende dagen','Stad, bijv. Amsterdam, Londen…','ZOEKEN','Weer laden…','Gevoelstemperatuur','Luchtvochtigheid','Wind','Regen','Vandaag','Weergegevens tijdelijk niet beschikbaar.','Stad niet gevonden.']};
const FLAGS={fr:'🇫🇷',be:'🇧🇪',ch:'🇨🇭',gb:'🇬🇧',us:'🇺🇸',ca:'🇨🇦',de:'🇩🇪',es:'🇪🇸',it:'🇮🇹',pt:'🇵🇹',nl:'🇳🇱'},icons={0:'☀️',1:'🌤️',2:'⛅',3:'☁️',45:'☁️',48:'☁️',51:'🌦️',53:'🌦️',55:'🌧️',56:'🌧️',57:'🌧️',61:'🌧️',63:'🌧️',65:'🌧️',66:'🌧️',67:'🌧️',71:'🌨️',73:'🌨️',75:'❄️',77:'🌨️',80:'🌦️',81:'🌦️',82:'🌧️',85:'🌨️',86:'❄️',95:'⛈️',96:'⛈️',99:'⛈️'};
let panel=null,region=localStorage.getItem('technorizon-weather-region')||'fr';if(!RL[region])region='fr';let current={lat:49.6684,lon:0.8955,name:'Yerville',country:'France',timezone:'Europe/Paris'};try{const s=JSON.parse(localStorage.getItem('technorizon-weather-location'));if(s?.lat&&s?.lon)current=s}catch(e){}
const close=()=>{if(panel){panel.remove();panel=null;document.body.style.overflow=''}};
function open(){if(panel)return;panel=document.createElement('section');panel.id='tz-spa-weather';panel.innerHTML='<div class="tz-weather-bg"></div><main class="tz-weather-panel"><div class="tz-weather-top"><button class="tz-weather-back"></button><select class="tz-weather-lang"></select></div><h1 class="tz-weather-title"></h1><p class="tz-weather-sub"></p><form class="tz-weather-search"><input type="search" autocomplete="off"><button type="submit"></button></form><div class="tz-weather-location"></div><div class="tz-weather-out"></div></main>';document.body.appendChild(panel);document.body.style.overflow='hidden';const back=panel.querySelector('.tz-weather-back'),sel=panel.querySelector('.tz-weather-lang'),title=panel.querySelector('.tz-weather-title'),sub=panel.querySelector('.tz-weather-sub'),form=panel.querySelector('.tz-weather-search'),input=form.querySelector('input'),searchBtn=form.querySelector('button'),loc=panel.querySelector('.tz-weather-location'),out=panel.querySelector('.tz-weather-out');back.onclick=close;
async function load(){const [lang,locale]=RL[region],x=T[lang];out.innerHTML='<div class="tz-weather-status">'+x[5]+'</div>';try{const u='https://api.open-meteo.com/v1/forecast?latitude='+current.lat+'&longitude='+current.lon+'&current=temperature_2m,apparent_temperature,weather_code,wind_speed_10m,relative_humidity_2m&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max&timezone='+encodeURIComponent(current.timezone||'auto')+'&forecast_days=5',r=await fetch(u,{cache:'no-store'}),d=await r.json(),n=d.current,dy=d.daily;loc.textContent='📍 '+current.name+(current.country?', '+current.country:'');const cards=dy.time.map((date,i)=>'<div class="tz-weather-day"><b>'+(i===0?x[10]:new Intl.DateTimeFormat(locale,{weekday:'short'}).format(new Date(date+'T12:00:00')))+'</b><div class="tz-weather-icon">'+(icons[dy.weather_code[i]]||'☁️')+'</div><strong>'+Math.round(dy.temperature_2m_min[i])+'° / '+Math.round(dy.temperature_2m_max[i])+'°</strong><small>'+x[9]+' '+(dy.precipitation_probability_max[i]??0)+'%</small></div>').join('');out.innerHTML='<div class="tz-weather-now"><div class="tz-weather-temp">'+Math.round(n.temperature_2m)+'°C</div><div class="tz-weather-condition">'+(icons[n.weather_code]||'☁️')+'</div><div>'+x[6]+' '+Math.round(n.apparent_temperature)+'°C • '+x[7]+' '+n.relative_humidity_2m+'% • '+x[8]+' '+Math.round(n.wind_speed_10m)+' km/h</div></div><div class="tz-weather-forecast">'+cards+'</div>'}catch(e){out.innerHTML='<div class="tz-weather-status">'+x[11]+'</div>'}}
async function search(q){const [lang]=RL[region],x=T[lang];try{const r=await fetch('https://geocoding-api.open-meteo.com/v1/search?name='+encodeURIComponent(q)+'&count=1&language='+lang+'&format=json',{cache:'no-store'}),d=await r.json(),p=d?.results?.[0];if(!p){out.innerHTML='<div class="tz-weather-status">'+x[12]+'</div>';return}current={lat:p.latitude,lon:p.longitude,name:p.name,country:p.country||'',timezone:p.timezone||'auto'};localStorage.setItem('technorizon-weather-location',JSON.stringify(current));load()}catch(e){out.innerHTML='<div class="tz-weather-status">'+x[11]+'</div>'}}
function render(){const [lang]=RL[region],x=T[lang];back.textContent=x[0];title.textContent=x[1];sub.textContent=x[2];input.placeholder=x[3];searchBtn.textContent=x[4];sel.innerHTML='';Object.keys(RL).forEach(r=>sel.add(new Option(FLAGS[r]+' '+r.toUpperCase(),r)));sel.value=region;load()}sel.onchange=()=>{region=sel.value;localStorage.setItem('technorizon-weather-region',region);render()};form.onsubmit=e=>{e.preventDefault();if(input.value.trim())search(input.value.trim())};render()}
link.addEventListener('click',e=>{if(e.button!==0||e.ctrlKey||e.metaKey||e.shiftKey||e.altKey)return;e.preventDefault();open()},true);
})();
