(()=>{
'use strict';
const mobileStyle=document.createElement('style');mobileStyle.textContent=`@media(max-width:760px){html,body,.v2-page{width:100%;max-width:100%;overflow-x:hidden!important}.v2-topbar{width:100%!important;min-height:auto!important;overflow:hidden!important}.v2-topbar-inner{box-sizing:border-box!important;width:100%!important;max-width:100%!important;min-height:auto!important;margin:0!important;padding:8px 8px!important;display:grid!important;grid-template-columns:minmax(96px,120px) 1fr auto!important;gap:5px!important;align-items:center!important}.v2-language{grid-column:1!important;min-width:0!important}.v2-language .lang-select{min-width:0!important;width:100%!important;max-width:120px!important;height:34px!important;padding:0 24px 0 8px!important;background-position:right 8px center!important;background-size:9px 6px!important;font-size:10px!important;text-align:left!important;white-space:nowrap!important}.v2-language .lang-select option{font-size:14px!important}.v2-nav{grid-column:2!important;display:flex!important;justify-content:center!important;gap:1px!important;min-width:0!important;overflow:hidden!important}.v2-nav a{display:flex!important;align-items:center!important;justify-content:center!important;width:30px!important;height:32px!important;padding:0!important;font-size:0!important;border-radius:8px!important}.v2-nav .nav-icon{font-size:15px!important;line-height:1!important}.v2-nav a span:not(.nav-icon){display:none!important}.v2-top-signature{display:none!important}.v2-top-socials{grid-column:3!important;display:flex!important;gap:2px!important;justify-content:flex-end!important;min-width:0!important}.v2-top-social{width:27px!important;height:27px!important;min-width:27px!important;font-size:10px!important}}@media(max-width:390px){.v2-topbar-inner{grid-template-columns:minmax(88px,105px) 1fr auto!important;padding:7px 5px!important;gap:2px!important}.v2-language .lang-select{max-width:105px!important;padding-left:6px!important;padding-right:19px!important;font-size:9px!important;background-position:right 6px center!important}.v2-nav a{width:27px!important;height:29px!important}.v2-nav .nav-icon{font-size:14px!important}.v2-top-social{width:24px!important;height:24px!important;min-width:24px!important;font-size:9px!important}}`;document.head.appendChild(mobileStyle);
const targets=['technoroscope.html','dedicaces.html','jeux.html','a-propos.html','contact.html'];
let layer=null;
const close=()=>{if(layer){layer.remove();layer=null;document.body.style.overflow=''}};
function open(url){if(layer)return;layer=document.createElement('section');layer.className='tz-native-layer';layer.innerHTML='<div class="tz-native-bg"></div><div class="tz-native-shell"><button type="button" class="tz-native-back">← Accueil</button><div class="tz-native-content">Chargement…</div></div>';document.body.appendChild(layer);document.body.style.overflow='hidden';layer.querySelector('.tz-native-back').onclick=close;const box=layer.querySelector('.tz-native-content');fetch(url,{cache:'no-store'}).then(r=>r.text()).then(html=>{const doc=new DOMParser().parseFromString(html,'text/html'),main=doc.querySelector('main');if(!main)throw Error();box.innerHTML=main.innerHTML;box.className='tz-native-content '+(main.className||'');box.querySelectorAll('a[href="index.html"],a[href="/"]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();close()}));const styles=[...doc.querySelectorAll('head style')].map(x=>x.textContent).join('\n');if(styles){const s=document.createElement('style');s.textContent='.tz-native-content '+styles.replace(/body/g,'.tz-native-content').replace(/\.page/g,'.tz-native-content .page').replace(/\.panel/g,'.tz-native-content .panel').replace(/\.box/g,'.tz-native-content .box');layer.appendChild(s)};const scripts=[...doc.scripts].filter(s=>s.src).map(s=>new URL(s.src,location.href).pathname);scripts.forEach(src=>{if(src.includes('persistent-radio'))return;const s=document.createElement('script');s.src=src+(src.includes('?')?'&':'?')+'spa=1';layer.appendChild(s)})}).catch(()=>{box.innerHTML='<p style="text-align:center;color:#aebdcb;padding:40px">Contenu momentanément indisponible.</p>'})}
document.addEventListener('click',e=>{const a=e.target.closest('a[href]');if(!a)return;const path=new URL(a.href,location.href).pathname.split('/').pop();if(!targets.includes(path))return;if(e.button!==0||e.ctrlKey||e.metaKey||e.shiftKey||e.altKey)return;e.preventDefault();open(path)},true);
})();
