(()=>{
'use strict';
const infosLink=document.querySelector('a[href="infos.html"].v2-card-link');
if(!infosLink)return;
const R={fr:'fr',be:'fr',ch:'fr',gb:'en',us:'en',ca:'fr',de:'de',es:'es',it:'it',pt:'pt',nl:'nl'};
const F={fr:'🇫🇷',be:'🇧🇪',ch:'🇨🇭',gb:'🇬🇧',us:'🇺🇸',ca:'🇨🇦',de:'🇩🇪',es:'🇪🇸',it:'🇮🇹',pt:'🇵🇹',nl:'🇳🇱'};
const T={fr:['← Retour à l’accueil','INFOS','L’actualité essentielle • La région choisie détermine les informations','Chargement des informations…','Les informations sont momentanément indisponibles.','ACTU','Lire la suite →'],en:['← Back to home','NEWS','Essential news • Your selected region determines the news','Loading news…','News is temporarily unavailable.','NEWS','Read more →'],de:['← Zurück zur Startseite','NEWS','Wichtige Nachrichten • Deine Region bestimmt die Nachrichten','Nachrichten werden geladen…','Nachrichten sind vorübergehend nicht verfügbar.','AKTUELL','Weiterlesen →'],es:['← Volver al inicio','NOTICIAS','Noticias esenciales • Tu región determina las noticias','Cargando noticias…','Las noticias no están disponibles temporalmente.','ACTUALIDAD','Leer más →'],it:['← Torna alla home','NOTIZIE','Notizie essenziali • La regione scelta determina le notizie','Caricamento notizie…','Le notizie non sono temporaneamente disponibili.','NEWS','Continua a leggere →'],pt:['← Voltar ao início','NOTÍCIAS','Notícias essenciais • A região escolhida determina as notícias','A carregar notícias…','As notícias estão temporariamente indisponíveis.','ATUALIDADE','Ler mais →'],nl:['← Terug naar home','NIEUWS','Belangrijk nieuws • Je gekozen regio bepaalt het nieuws','Nieuws laden…','Nieuws is tijdelijk niet beschikbaar.','NIEUWS','Lees verder →']};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));\nconst getTime=(v,lang)=>{const raw=v.publishedAt||v.pubDate||v.date||v.published_at;if(!raw)return'';const d=new Date(raw);if(Number.isNaN(d.getTime()))return'';const locales={fr:'fr-FR',en:'en-GB',de:'de-DE',es:'es-ES',it:'it-IT',pt:'pt-PT',nl:'nl-NL'};return d.toLocaleTimeString(locales[lang]||'fr-FR',{hour:'2-digit',minute:'2-digit'})};
let panel=null,region=localStorage.getItem('technorizon-region')||'fr';if(!R[region])region='fr';
function close(){if(panel){panel.remove();panel=null;document.body.style.overflow='';}}
async function load(list,lang){const x=T[lang]||T.fr;list.innerHTML='<div class="tz-spa-status">'+x[3]+'</div>';try{const r=await fetch('/api/news?country='+region,{cache:'no-store'}),d=await r.json(),items=Array.isArray(d?.items)?d.items.filter(v=>v?.title):[];if(!items.length)throw Error();list.innerHTML=items.slice(0,10).map(v=>{const url=String(v.link||'').trim(),source=esc(v.source?.name||v.source||'Technorizon'),time=getTime(v,lang);const inner='<div class="tz-spa-meta"><span>'+x[5]+'</span>'+(time?'<span>'+time+'</span>':'')+'</div><div class="tz-spa-news-title">'+esc(v.title)+'</div><div class="tz-spa-source">'+source+'</div>'+(url?'<div class="tz-spa-readmore">'+x[6]+'</div>':'');return url?'<a class="tz-spa-news" href="'+esc(url)+'" target="_blank" rel="noopener noreferrer">'+inner+'</a>':'<article class="tz-spa-news">'+inner+'</article>'}).join('')}catch(e){list.innerHTML='<div class="tz-spa-status">'+x[4]+'</div>'}}
function open(){if(panel)return;panel=document.createElement('section');panel.id='tz-spa-infos';panel.innerHTML='<div class="tz-spa-bg"></div><div class="tz-spa-panel"><div class="tz-spa-top"><button class="tz-spa-back" type="button"></button><select class="tz-spa-lang"></select></div><h1 class="tz-spa-title"></h1><p class="tz-spa-sub"></p><div class="tz-spa-list"></div></div>';document.body.appendChild(panel);document.body.style.overflow='hidden';const back=panel.querySelector('.tz-spa-back'),sel=panel.querySelector('.tz-spa-lang'),title=panel.querySelector('.tz-spa-title'),sub=panel.querySelector('.tz-spa-sub'),list=panel.querySelector('.tz-spa-list');function render(){const lang=R[region]||'fr',x=T[lang]||T.fr;back.textContent=x[0];title.textContent=x[1];sub.textContent=x[2];sel.innerHTML='';Object.keys(R).forEach(r=>sel.add(new Option(F[r]+' '+r.toUpperCase(),r)));sel.value=region;load(list,lang)}back.onclick=close;sel.onchange=()=>{region=sel.value;localStorage.setItem('technorizon-region',region);localStorage.setItem('technorizon-lang',R[region]);render()};render()}
infosLink.addEventListener('click',e=>{if(e.button!==0||e.ctrlKey||e.metaKey||e.shiftKey||e.altKey)return;e.preventDefault();open()},true);
})();
