const data={
  fr:{intro:'Découvrez votre horoscope du jour version Technorizon.',back:"← Retour à l'accueil",choose:'Sélectionnez votre signe pour découvrir votre Technoroscope du jour.',signs:{belier:['Bélier','Votre énergie est en mode BPM élevé. Profitez de cet élan pour avancer sur ce qui vous tient vraiment à cœur.'],taureau:['Taureau','Gardez votre tempo. Inutile d’accélérer aujourd’hui : les meilleures choses arrivent au bon rythme.'],gemeaux:['Gémeaux','Une rencontre ou un message pourrait changer la tonalité de votre journée. Restez attentif aux signaux.'],cancer:['Cancer','Écoutez votre intuition : aujourd’hui, elle semble parfaitement calée sur la bonne fréquence.'],lion:['Lion','Les projecteurs sont sur vous. Assumez votre énergie et faites entendre votre différence.'],vierge:['Vierge','Quelques réglages suffiront à remettre votre journée dans le tempo. Ne cherchez pas à tout contrôler.'],balance:['Balance','Cherchez l’harmonie sans oublier votre propre mélodie. Un compromis pourrait débloquer une situation.'],scorpion:['Scorpion','L’intensité monte aujourd’hui. Utilisez cette énergie pour avancer sans pousser le volume trop loin.'],sagittaire:['Sagittaire','Besoin d’air et de nouveauté ? Changez de route, de playlist ou simplement de perspective.'],capricorne:['Capricorne','Votre constance commence à payer. Continuez d’avancer piste après piste : le résultat se rapproche.'],verseau:['Verseau','Une idée originale pourrait faire toute la différence. Aujourd’hui, osez sortir du format.'],poissons:['Poissons','Laissez parler votre sensibilité. Certaines émotions méritent simplement d’être écoutées.']}},
  en:{intro:'Discover your daily horoscope, Technorizon edition.',back:'← Back to home',choose:'Select your zodiac sign to discover your Technoroscope for today.',signs:{belier:['Aries','Your energy is running at a high BPM. Use this momentum to move forward on what truly matters to you.'],taureau:['Taurus','Keep your tempo. There is no need to speed up today: the best things arrive at the right rhythm.'],gemeaux:['Gemini','A meeting or message could change the tone of your day. Stay alert to the signals around you.'],cancer:['Cancer','Trust your intuition: today it seems perfectly tuned to the right frequency.'],lion:['Leo','The spotlight is on you. Own your energy and let your difference be heard.'],vierge:['Virgo','A few adjustments will be enough to put your day back on tempo. Do not try to control everything.'],balance:['Libra','Look for harmony without forgetting your own melody. A compromise could unlock a situation.'],scorpion:['Scorpio','The intensity is rising today. Use that energy to move forward without pushing the volume too far.'],sagittaire:['Sagittarius','Need some fresh air and something new? Change your route, your playlist, or simply your perspective.'],capricorne:['Capricorn','Your consistency is starting to pay off. Keep moving forward track by track.'],verseau:['Aquarius','An original idea could make all the difference. Dare to step outside the format.'],poissons:['Pisces','Let your sensitivity speak. Some emotions simply deserve to be listened to.']}},
  es:{intro:'Descubre tu horóscopo diario, edición Technorizon.',back:'← Volver al inicio',choose:'Selecciona tu signo para descubrir tu Technoroscope de hoy.',signs:{belier:['Aries','Tu energía está a un BPM elevado. Aprovecha este impulso para avanzar en lo que realmente te importa.'],taureau:['Tauro','Mantén tu ritmo. Hoy no necesitas acelerar: las mejores cosas llegan a su debido tiempo.'],gemeaux:['Géminis','Un encuentro o un mensaje podría cambiar el tono de tu día. Presta atención a las señales.'],cancer:['Cáncer','Confía en tu intuición: hoy parece estar perfectamente sintonizada con la frecuencia adecuada.'],lion:['Leo','Los focos están sobre ti. Asume tu energía y haz que se escuche tu diferencia.'],vierge:['Virgo','Unos pequeños ajustes bastarán para devolver el ritmo a tu día. No intentes controlarlo todo.'],balance:['Libra','Busca la armonía sin olvidar tu propia melodía. Un acuerdo podría desbloquear una situación.'],scorpion:['Escorpio','La intensidad aumenta hoy. Usa esa energía para avanzar sin subir demasiado el volumen.'],sagittaire:['Sagitario','¿Necesitas aire fresco y novedades? Cambia de ruta, de lista musical o simplemente de perspectiva.'],capricorne:['Capricornio','Tu constancia empieza a dar frutos. Sigue avanzando pista a pista.'],verseau:['Acuario','Una idea original podría marcar la diferencia. Atrévete a salir del formato.'],poissons:['Piscis','Deja hablar a tu sensibilidad. Algunas emociones simplemente merecen ser escuchadas.']}},
  de:{intro:'Entdecke dein Tageshoroskop in der Technorizon-Edition.',back:'← Zurück zur Startseite',choose:'Wähle dein Sternzeichen für dein heutiges Technoroscope.',signs:{belier:['Widder','Deine Energie läuft heute auf hohem BPM-Niveau. Nutze diesen Schwung für das, was dir wirklich wichtig ist.'],taureau:['Stier','Halte dein Tempo. Du musst heute nichts beschleunigen: Die besten Dinge kommen im richtigen Rhythmus.'],gemeaux:['Zwillinge','Eine Begegnung oder Nachricht könnte den Ton deines Tages verändern. Achte auf die Signale.'],cancer:['Krebs','Vertraue deiner Intuition: Heute ist sie perfekt auf die richtige Frequenz eingestellt.'],lion:['Löwe','Das Rampenlicht gehört dir. Steh zu deiner Energie und zeige, was dich besonders macht.'],vierge:['Jungfrau','Ein paar kleine Anpassungen bringen deinen Tag wieder in den Takt. Versuche nicht, alles zu kontrollieren.'],balance:['Waage','Suche Harmonie, ohne deine eigene Melodie zu vergessen. Ein Kompromiss könnte etwas lösen.'],scorpion:['Skorpion','Die Intensität steigt heute. Nutze diese Energie, ohne die Lautstärke zu weit aufzudrehen.'],sagittaire:['Schütze','Brauchst du frische Luft und etwas Neues? Ändere die Route, die Playlist oder einfach deine Perspektive.'],capricorne:['Steinbock','Deine Beständigkeit zahlt sich langsam aus. Geh Track für Track weiter.'],verseau:['Wassermann','Eine originelle Idee könnte den Unterschied machen. Wage heute den Schritt aus dem gewohnten Format.'],poissons:['Fische','Lass deine Sensibilität sprechen. Manche Gefühle wollen einfach gehört werden.']}},
  it:{intro:'Scopri il tuo oroscopo quotidiano, edizione Technorizon.',back:'← Torna alla home',choose:'Seleziona il tuo segno per scoprire il Technoroscope di oggi.',signs:{belier:['Ariete','La tua energia viaggia a BPM elevati. Sfrutta questo slancio per ciò che conta davvero per te.'],taureau:['Toro','Mantieni il tuo ritmo. Oggi non serve accelerare: le cose migliori arrivano al momento giusto.'],gemeaux:['Gemelli','Un incontro o un messaggio potrebbe cambiare il tono della giornata. Fai attenzione ai segnali.'],cancer:['Cancro','Fidati del tuo intuito: oggi sembra perfettamente sintonizzato sulla frequenza giusta.'],lion:['Leone','I riflettori sono puntati su di te. Mostra la tua energia e fai sentire la tua unicità.'],vierge:['Vergine','Basteranno pochi aggiustamenti per riportare la giornata a tempo. Non cercare di controllare tutto.'],balance:['Bilancia','Cerca l’armonia senza dimenticare la tua melodia. Un compromesso potrebbe sbloccare una situazione.'],scorpion:['Scorpione','Oggi l’intensità aumenta. Usa questa energia per avanzare senza alzare troppo il volume.'],sagittaire:['Sagittario','Hai bisogno di aria nuova? Cambia strada, playlist o semplicemente prospettiva.'],capricorne:['Capricorno','La tua costanza comincia a dare risultati. Continua ad avanzare, traccia dopo traccia.'],verseau:['Acquario','Un’idea originale potrebbe fare la differenza. Oggi osa uscire dagli schemi.'],poissons:['Pesci','Lascia parlare la tua sensibilità. Alcune emozioni meritano semplicemente di essere ascoltate.']}},
  nl:{intro:'Ontdek je dagelijkse horoscoop, Technorizon-editie.',back:'← Terug naar home',choose:'Kies je sterrenbeeld voor je Technoroscope van vandaag.',signs:{belier:['Ram','Je energie draait op een hoog BPM. Gebruik deze impuls voor wat echt belangrijk voor je is.'],taureau:['Stier','Houd je eigen tempo aan. Je hoeft vandaag niet te versnellen: de beste dingen komen op het juiste ritme.'],gemeaux:['Tweelingen','Een ontmoeting of bericht kan de toon van je dag veranderen. Let goed op de signalen.'],cancer:['Kreeft','Vertrouw op je intuïtie: vandaag staat die perfect op de juiste frequentie afgestemd.'],lion:['Leeuw','De spotlights staan op jou. Omarm je energie en laat horen wat jou anders maakt.'],vierge:['Maagd','Een paar aanpassingen brengen je dag weer in het juiste tempo. Probeer niet alles te beheersen.'],balance:['Weegschaal','Zoek harmonie zonder je eigen melodie te vergeten. Een compromis kan iets losmaken.'],scorpion:['Schorpioen','De intensiteit neemt vandaag toe. Gebruik die energie zonder het volume te ver open te draaien.'],sagittaire:['Boogschutter','Behoefte aan frisse lucht en iets nieuws? Verander je route, playlist of gewoon je perspectief.'],capricorne:['Steenbok','Je volharding begint vruchten af te werpen. Ga nummer voor nummer verder.'],verseau:['Waterman','Een origineel idee kan het verschil maken. Durf vandaag buiten het vaste format te treden.'],poissons:['Vissen','Laat je gevoeligheid spreken. Sommige emoties verdienen het om gewoon gehoord te worden.']}},
  pt:{intro:'Descobre o teu horóscopo diário, edição Technorizon.',back:'← Voltar ao início',choose:'Seleciona o teu signo para descobrires o Technoroscope de hoje.',signs:{belier:['Carneiro','A tua energia está com um BPM elevado. Aproveita este impulso para avançar no que realmente importa.'],taureau:['Touro','Mantém o teu ritmo. Hoje não precisas de acelerar: as melhores coisas chegam no tempo certo.'],gemeaux:['Gémeos','Um encontro ou uma mensagem pode mudar o tom do teu dia. Fica atento aos sinais.'],cancer:['Caranguejo','Confia na tua intuição: hoje parece perfeitamente sintonizada na frequência certa.'],lion:['Leão','Os holofotes estão sobre ti. Assume a tua energia e mostra o que te torna diferente.'],vierge:['Virgem','Alguns ajustes serão suficientes para devolver ritmo ao teu dia. Não tentes controlar tudo.'],balance:['Balança','Procura harmonia sem esquecer a tua própria melodia. Um compromisso pode desbloquear uma situação.'],scorpion:['Escorpião','A intensidade aumenta hoje. Usa essa energia para avançar sem subir demasiado o volume.'],sagittaire:['Sagitário','Precisas de ar fresco e novidade? Muda de caminho, de playlist ou simplesmente de perspetiva.'],capricorne:['Capricórnio','A tua consistência começa a dar frutos. Continua a avançar faixa após faixa.'],verseau:['Aquário','Uma ideia original pode fazer toda a diferença. Hoje, ousa sair do formato.'],poissons:['Peixes','Deixa a tua sensibilidade falar. Algumas emoções merecem simplesmente ser ouvidas.']}}
};

const astroPools={
  fr:{work:['Une priorité mérite toute votre attention. En évitant la dispersion, vous avancerez plus vite que prévu.','Une idée simple peut convaincre. Présentez-la avec confiance et laissez parler votre savoir-faire.','Une collaboration devient porteuse si chacun exprime clairement ses attentes.','Un contretemps n’est pas un échec : ajustez votre méthode et gardez votre cap.'],love:['Un geste sincère comptera plus qu’une grande déclaration. La douceur favorise les rapprochements.','Dites ce que vous ressentez sans chercher la formule parfaite : l’authenticité créera la connexion.','Une conversation légère peut dissiper une tension. L’humour sera votre meilleur allié.','Laissez un peu d’espace à l’autre tout en restant présent : cet équilibre renforcera la confiance.'],health:['Votre énergie est bonne, mais quelques pauses vous aideront à conserver ce rythme jusqu’au soir.','Un peu de mouvement et quelques respirations profondes vous aideront à relâcher les tensions.','Votre corps réclame un tempo plus doux. Écoutez ses signaux et accordez davantage de place au repos.','Hydratation, repas réguliers et sommeil seront vos meilleurs alliés pour préserver votre équilibre.']},
  en:{work:['One priority deserves your full attention. Avoiding distractions will help you move forward faster than expected.','A simple idea can persuade. Present it confidently and let your skills speak for themselves.','A collaboration becomes promising when everyone clearly expresses their expectations.','A delay is not a failure: adjust your method and stay on course.'],love:['A sincere gesture will matter more than a grand declaration. Kindness encourages closeness.','Say what you feel without searching for perfect words: authenticity will create the connection.','A light-hearted conversation can clear away tension. Humour is your best ally today.','Give the other person some space while remaining present: that balance will strengthen trust.'],health:['Your energy is good, but a few breaks will help you maintain that rhythm until the evening.','A little movement and a few deep breaths will help release accumulated tension.','Your body is asking for a gentler tempo. Listen to its signals and make more room for rest.','Hydration, regular meals and sleep will be your best allies in maintaining balance.']},
  es:{work:['Una prioridad merece toda tu atención. Evitar distracciones te permitirá avanzar más rápido de lo previsto.','Una idea sencilla puede convencer. Preséntala con confianza y deja que hable tu experiencia.','Una colaboración se vuelve prometedora cuando cada persona expresa claramente sus expectativas.','Un contratiempo no es un fracaso: ajusta tu método y mantén el rumbo.'],love:['Un gesto sincero contará más que una gran declaración. La ternura favorecerá el acercamiento.','Di lo que sientes sin buscar las palabras perfectas: la autenticidad creará la conexión.','Una conversación ligera puede disipar una tensión. El humor será tu mejor aliado.','Da espacio a la otra persona sin dejar de estar presente: ese equilibrio reforzará la confianza.'],health:['Tu energía es buena, pero algunas pausas te ayudarán a mantener el ritmo hasta la noche.','Un poco de movimiento y unas respiraciones profundas ayudarán a liberar tensiones.','Tu cuerpo pide un ritmo más suave. Escucha sus señales y deja más espacio al descanso.','La hidratación, las comidas regulares y el sueño serán tus mejores aliados.']},
  de:{work:['Eine Priorität verdient deine volle Aufmerksamkeit. Ohne Ablenkung kommst du schneller voran als erwartet.','Eine einfache Idee kann überzeugen. Präsentiere sie selbstbewusst und lass dein Können sprechen.','Eine Zusammenarbeit wird vielversprechend, wenn alle ihre Erwartungen klar aussprechen.','Eine Verzögerung ist kein Scheitern: Passe deine Methode an und bleib auf Kurs.'],love:['Eine ehrliche Geste zählt mehr als eine große Erklärung. Zuneigung bringt euch näher.','Sag, was du fühlst, ohne nach perfekten Worten zu suchen: Echtheit schafft Verbindung.','Ein lockeres Gespräch kann Spannungen lösen. Humor ist heute dein bester Verbündeter.','Gib deinem Gegenüber Raum und bleib zugleich präsent: Dieses Gleichgewicht stärkt das Vertrauen.'],health:['Deine Energie ist gut, doch ein paar Pausen helfen dir, den Rhythmus bis zum Abend zu halten.','Etwas Bewegung und einige tiefe Atemzüge helfen, Spannungen zu lösen.','Dein Körper wünscht sich ein sanfteres Tempo. Höre auf seine Signale und gönne dir mehr Ruhe.','Ausreichend Wasser, regelmäßige Mahlzeiten und Schlaf bewahren dein Gleichgewicht.']},
  it:{work:['Una priorità merita tutta la tua attenzione. Evitando le distrazioni avanzerai più rapidamente del previsto.','Un’idea semplice può convincere. Presentala con fiducia e lascia parlare le tue capacità.','Una collaborazione diventa promettente quando tutti esprimono chiaramente le proprie aspettative.','Un contrattempo non è un fallimento: adatta il metodo e mantieni la rotta.'],love:['Un gesto sincero conterà più di una grande dichiarazione. La dolcezza favorirà la vicinanza.','Di’ ciò che provi senza cercare le parole perfette: l’autenticità creerà la connessione.','Una conversazione leggera può sciogliere una tensione. L’umorismo sarà il tuo migliore alleato.','Lascia un po’ di spazio all’altra persona restando presente: questo equilibrio rafforzerà la fiducia.'],health:['La tua energia è buona, ma qualche pausa ti aiuterà a mantenere il ritmo fino a sera.','Un po’ di movimento e alcuni respiri profondi aiuteranno a sciogliere le tensioni.','Il tuo corpo chiede un ritmo più dolce. Ascolta i suoi segnali e dedica più spazio al riposo.','Idratazione, pasti regolari e sonno saranno i tuoi migliori alleati.']},
  nl:{work:['Eén prioriteit verdient al je aandacht. Zonder afleiding ga je sneller vooruit dan verwacht.','Een eenvoudig idee kan overtuigen. Breng het met vertrouwen en laat je vakmanschap spreken.','Een samenwerking wordt kansrijk wanneer iedereen duidelijk zijn verwachtingen uitspreekt.','Een tegenslag is geen mislukking: pas je aanpak aan en blijf op koers.'],love:['Een oprecht gebaar telt meer dan een grote verklaring. Zachtheid brengt jullie dichter bij elkaar.','Zeg wat je voelt zonder naar perfecte woorden te zoeken: oprechtheid zorgt voor verbinding.','Een luchtig gesprek kan spanning wegnemen. Humor is vandaag je beste bondgenoot.','Geef de ander wat ruimte en blijf tegelijk aanwezig: dat evenwicht versterkt het vertrouwen.'],health:['Je energie is goed, maar enkele pauzes helpen je om dit ritme tot vanavond vol te houden.','Wat beweging en een paar diepe ademhalingen helpen opgebouwde spanning los te laten.','Je lichaam vraagt om een rustiger tempo. Luister naar de signalen en maak meer ruimte voor herstel.','Water, regelmatige maaltijden en slaap zijn je beste bondgenoten voor balans.']},
  pt:{work:['Uma prioridade merece toda a tua atenção. Ao evitares distrações, avançarás mais depressa do que esperavas.','Uma ideia simples pode convencer. Apresenta-a com confiança e deixa as tuas competências falar.','Uma colaboração torna-se promissora quando todos expressam claramente as suas expectativas.','Um contratempo não é um fracasso: ajusta o método e mantém o rumo.'],love:['Um gesto sincero contará mais do que uma grande declaração. A ternura favorecerá a aproximação.','Diz o que sentes sem procurar as palavras perfeitas: a autenticidade criará a ligação.','Uma conversa leve pode dissipar uma tensão. O humor será o teu melhor aliado.','Dá algum espaço à outra pessoa sem deixares de estar presente: esse equilíbrio reforçará a confiança.'],health:['A tua energia está boa, mas algumas pausas ajudarão a manter o ritmo até ao fim do dia.','Um pouco de movimento e algumas respirações profundas ajudarão a aliviar as tensões.','O teu corpo pede um ritmo mais suave. Escuta os sinais e reserva mais espaço para o descanso.','Hidratação, refeições regulares e sono serão os teus melhores aliados para manter o equilíbrio.']}
};

const astroUi={
  fr:{trend:'Tendance du jour',work:'Travail',love:'Amour',health:'Santé',rating:'Indice',note:'Le Technoroscope est proposé pour le divertissement.',locale:'fr-FR',outOf:'sur'},
  en:{trend:"Today's outlook",work:'Work',love:'Love',health:'Well-being',rating:'Rating',note:'The Technoroscope is provided for entertainment purposes.',locale:'en-GB',outOf:'out of'},
  es:{trend:'Tendencia del día',work:'Trabajo',love:'Amor',health:'Salud',rating:'Índice',note:'El Technoroscope se ofrece con fines de entretenimiento.',locale:'es-ES',outOf:'de'},
  de:{trend:'Tagestendenz',work:'Arbeit',love:'Liebe',health:'Gesundheit',rating:'Wertung',note:'Das Technoroscope dient der Unterhaltung.',locale:'de-DE',outOf:'von'},
  it:{trend:'Tendenza del giorno',work:'Lavoro',love:'Amore',health:'Salute',rating:'Indice',note:'Il Technoroscope è proposto a scopo di intrattenimento.',locale:'it-IT',outOf:'su'},
  nl:{trend:'Trend van vandaag',work:'Werk',love:'Liefde',health:'Gezondheid',rating:'Score',note:'De Technoroscope is uitsluitend bedoeld voor entertainment.',locale:'nl-NL',outOf:'van'},
  pt:{trend:'Tendência do dia',work:'Trabalho',love:'Amor',health:'Saúde',rating:'Índice',note:'O Technoroscope é disponibilizado para fins de entretenimento.',locale:'pt-PT',outOf:'de'}
};

const symbols={belier:'♈',taureau:'♉',gemeaux:'♊',cancer:'♋',lion:'♌',vierge:'♍',balance:'♎',scorpion:'♏',sagittaire:'♐',capricorne:'♑',verseau:'♒',poissons:'♓'};
const supportedLanguages=Object.keys(data);
const result=document.getElementById('result');
const buttons=[...document.querySelectorAll('.signs button')];
const savedLanguage=localStorage.getItem('technorizon-horoscope-lang')||localStorage.getItem('technorizon-jaya-lang')||localStorage.getItem('technorizon-lang');
let lang=supportedLanguages.includes(savedLanguage)?savedLanguage:'fr';
let selected=null;

function astroHash(value){let h=2166136261;for(let i=0;i<value.length;i++){h^=value.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function dailyValue(category,modulo){const now=new Date(),day=now.getFullYear()+'-'+(now.getMonth()+1)+'-'+now.getDate();return astroHash(day+'-'+selected+'-'+category)%modulo}
function categoryCard(key,icon,cssClass){const copy=astroUi[lang],messages=astroPools[lang][key],level=2+dailyValue(key,4),message=messages[dailyValue(key,messages.length)];return '<article class="astro-card '+cssClass+'"><div class="astro-card-top"><h3>'+icon+' '+copy[key]+'</h3><span class="astro-score" aria-label="'+copy.rating+' '+level+' '+copy.outOf+' 5">'+copy.rating+' : '+level+'/5</span></div><div class="astro-meter" aria-hidden="true">'+[1,2,3,4,5].map(n=>'<span class="'+(n<=level?'on':'')+'"></span>').join('')+'</div><p>'+message+'</p></article>'}
function render(){const copy=astroUi[lang];document.documentElement.lang=lang;langSelect.value=lang;intro.textContent=data[lang].intro;back.textContent=data[lang].back;buttons.forEach(button=>button.querySelector('span').textContent=data[lang].signs[button.dataset.sign][0]);if(!selected){result.classList.remove('visible');result.textContent=data[lang].choose;return}const sign=data[lang].signs[selected],date=new Intl.DateTimeFormat(copy.locale,{weekday:'long',day:'numeric',month:'long'}).format(new Date());result.classList.add('visible');result.innerHTML='<div class="result-head"><h2 class="result-sign">'+symbols[selected]+' '+sign[0]+'</h2><div class="result-date">'+copy.trend+' · '+date+'</div><p class="result-summary">'+sign[1]+'</p></div><div class="astro-indices">'+categoryCard('work','💼','astro-card-work')+categoryCard('love','❤️','astro-card-love')+categoryCard('health','🌿','astro-card-health')+'</div><p class="astro-note">'+copy.note+'</p>'}
function setLang(nextLanguage){lang=supportedLanguages.includes(nextLanguage)?nextLanguage:'fr';localStorage.setItem('technorizon-horoscope-lang',lang);render()}
langSelect.addEventListener('change',event=>setLang(event.target.value));
buttons.forEach(button=>button.addEventListener('click',()=>{selected=button.dataset.sign;buttons.forEach(item=>item.classList.toggle('active',item===button));render();result.scrollIntoView({behavior:'smooth',block:'nearest'})}));
render();
