/* Independent vinyl platter: never rotate the chassis or tonearm. */
(()=>{const host=document.querySelector('.tz-skin-host'),audio=document.getElementById('v2-audio'),play=document.getElementById('v2-play');if(!host||!audio||!play)return;
const deck=document.createElement('div');deck.className='tz-vinyl';deck.innerHTML='<div class="tz-vinyl-title"><b>TECHNORIZON</b><small>VINYL EDITION · 33⅓ RPM</small></div><div class="tz-vinyl-body"><div class="tz-vinyl-platter"><div class="tz-vinyl-label">TECHNORIZON<small>LA MUSIQUE SANS FRONTIÈRES</small></div></div><div class="tz-vinyl-arm"><svg class="tz-vinyl-arm-svg" viewBox="0 0 600 400" preserveAspectRatio="none" aria-hidden="true"><defs><linearGradient id="tz-vinyl-gold-tube" x1="0" x2="1"><stop stop-color="#856326"/><stop offset=".36" stop-color="#ffe6a2"/><stop offset=".68" stop-color="#d3a64d"/><stop offset="1" stop-color="#6e5428"/></linearGradient><radialGradient id="tz-vinyl-bearing-metal"><stop stop-color="#151a19"/><stop offset=".45" stop-color="#9c7734"/><stop offset=".72" stop-color="#e7c875"/><stop offset="1" stop-color="#42351d"/></radialGradient></defs><g class="tz-vinyl-arm-moving"><path d="M518 75 L502 150 Q500 163 488 170 L363 204" fill="none" stroke="#182626" stroke-width="13" stroke-linejoin="round"/><path d="M518 75 L502 150 Q500 163 488 170 L363 204" fill="none" stroke="url(#tz-vinyl-gold-tube)" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/><path d="M405 212 L382 224" stroke="#f0d188" stroke-width="9" stroke-linecap="round"/><rect x="330" y="208" width="24" height="15" rx="3" fill="#c9a251" stroke="#5c4628" stroke-width="2" transform="rotate(-25 342 215)"/><path d="M338 221 l-2 11" stroke="#f6edc5" stroke-width="2"/></g><circle cx="518" cy="75" r="28" fill="url(#tz-vinyl-bearing-metal)" stroke="#f2d48a" stroke-width="4"/><circle cx="518" cy="75" r="10" fill="#1c2421" stroke="#d7b15c" stroke-width="4"/></svg></div><div class="tz-vinyl-pitch"></div><div class="tz-vinyl-strobe"></div><div class="tz-vinyl-power"></div><button type="button" class="tz-vinyl-start" aria-label="Lecture ou pause">START / STOP</button></div><div class="tz-vinyl-meta"><strong id="tz-vinyl-track">Technorizon.fr</strong><span id="tz-vinyl-artist">La musique sans frontières</span></div>';host.appendChild(deck);
const btn=deck.querySelector('.tz-vinyl-start');btn.addEventListener('click',()=>play.click());
const track=document.getElementById('v2-track'),artist=document.getElementById('v2-artist');
const sync=()=>{host.classList.toggle('is-playing',!audio.paused&&!audio.ended);const t=document.getElementById('tz-vinyl-track'),a=document.getElementById('tz-vinyl-artist');if(t&&track)t.textContent=track.textContent;if(a&&artist)a.textContent=artist.textContent;};
['play','playing','pause','ended','emptied','error'].forEach(event=>audio.addEventListener(event,sync));
if(track)new MutationObserver(sync).observe(track,{childList:true,subtree:true,characterData:true});
if(artist)new MutationObserver(sync).observe(artist,{childList:true,subtree:true,characterData:true});
sync();
})();
