-- Promotion additive et réversible depuis staging vers une table dédiée.
-- Ne modifie PAS artists/tracks/knowledge existants.
create table if not exists public.jaya_knowledge_v1_ext (
 id bigint generated by default as identity primary key,
 staging_id bigint not null unique references public.jaya_knowledge_staging(id),
 domain text not null,
 entity_type text,
 canonical_name text not null,
 aliases jsonb not null default '[]'::jsonb,
 facts jsonb not null default '{}'::jsonb,
 source_name text not null,
 source_url text,
 source_id text,
 confidence numeric(4,3),
 batch_id text not null,
 promoted_at timestamptz not null default now()
);
alter table public.jaya_knowledge_v1_ext enable row level security;

-- Promotion uniquement des lignes explicitement approuvées.
-- INSERT INTO public.jaya_knowledge_v1_ext (...)
-- SELECT ... FROM public.jaya_knowledge_staging
-- WHERE review_status='approved' AND active=false AND batch_id=:batch_id;
