-- Jaya Brain V1 - zone d'enrichissement sécurisée
-- À appliquer en staging avant toute activation en production.

create table if not exists public.jaya_knowledge_staging (
  id bigint generated by default as identity primary key,
  domain text not null,
  entity_type text,
  canonical_name text not null,
  aliases jsonb not null default '[]'::jsonb,
  facts jsonb not null default '{}'::jsonb,
  source_name text not null,
  source_url text,
  source_id text,
  source_date timestamptz,
  confidence numeric(4,3) not null default 0.500 check (confidence between 0 and 1),
  fingerprint text not null,
  batch_id text not null,
  review_status text not null default 'pending' check (review_status in ('pending','approved','rejected','needs_review')),
  active boolean not null default false,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  unique(fingerprint)
);

create index if not exists jaya_knowledge_staging_review_idx
  on public.jaya_knowledge_staging(review_status, domain);
create index if not exists jaya_knowledge_staging_batch_idx
  on public.jaya_knowledge_staging(batch_id);

-- Sécurité: les imports restent inactifs jusqu'à validation explicite.
alter table public.jaya_knowledge_staging enable row level security;
